### ISSUE TITLE
[Problem] External geometry can't be converted to normal geometry

### ISSUE THREAD

**Issue by TomaszSzt** [FreeCAD/FreeCAD#10043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Polish/Poland (pl_PL) <-- actually I am running it with EN language.
Installed mods: 
  * Manipulator 1.5.0
  * QuickMeasure 2022.10.28
```

### Subproject(s) affected?

None

### Problem description

In the "part design->sketcher" environment there is an option to project "external geometry". Works fine.

From what I read at the forum the "external geometry" is treated as "construction geometry". A construction geometry can be changed to "normal" and vice versa with 
Tasks->elements->Mode:Contruction, selecting it on a list and right-clicking "Toggle construction line".

This option is available also for "External" elements. Using it has however no effect.

Steps to reproduce:

1.Create some body.
2.Place sketch on it.
3.Use "External geometry" to project some edge.
4.Select that projected edge in Tasks->Element list.
5.Right click.
6.Observe that:
 6.1. The "Toggle construction line" is NOT grayed out.
 6.2. Using it has no effect.

Expected behavior (best):
The "External" should be able to act as "Normal" or "Construction" after toggle.

Minimum acceptable behavior:
The options which are not applicable to current selection should be grayed out. 

Thanks for good work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
It's a known limitation, external (projected) geometry has to be outlined with sketcher tools to make use of it. But in the Realthunder's version of FreeCAD (so called Link Branch) there's a Defining geometry tool that let's you project the geometry for use in 3D operations. Give it a try. And check this wiki page (also available in Polish) about the current limitations of FreeCAD and available workarounds: https://wiki.freecad.org/Workarounds

Finally, please add some meaningful title like "External geometry can't be converted to normal geometry".

**Comment by TomaszSzt** [comment]
Thanks. Sorry for a title, I wasn't aware that [Problem] in a template is something I need to fill in as a title.

If graying out the inactive option base on selection is too cumbersome to do, some error message in "Report View" would be sufficient. Without it a beginner do hunt "what I did wrong?" for hours trying and trying.

**Comment by NXTler** [comment]
This

**Comment by maxwxyz** [comment]
My most wanted feature in sketcher...

I currently have to redraw all references which is very time consuming.

**Comment by PaddleStroke** [comment]
Having the construction toggle accept external geos to turn them into normal geometries makes sense to me as a feature request.

**Comment by FlachyJoe** [comment]
IMHO the External shouldn't be converted to Normal geometry but a normal should be created in top of it and constraints to it so linkage is preserved.

**Comment by maxwxyz** [comment]
why? I get that this workaround is easy when referencing one edge or a point but when referencing complex geometry you have to create all arches, lines, splines again on top of the references. It would be easy if selected references could be switched to active sketch geometry and construction geom (or what type it is today).

**Comment by FlachyJoe** [comment]
What I mean is that the normal geometry creation can be automatized but if you delete the external then you need to create another one to constraint the converted geometry.
It's certainly not a wanted behavior to get a free geometry from a fully constraints one.

**Comment by maxwxyz** [comment]
I dont want to create additional (even automated) geometry from the references but switch the already existing reference geometry to act like normal geometry and back (like the toggle for construction geo). So either it is there and constrained (because its pulled in as a reference) or not. And when the reference is there, either it is usable as any other fully constrained (but not editable) geometry to implement into my sketch or I toggle it as a kind of construction geometry (similar to now).

**Comment by FlachyJoe** [comment]
> switch the already existing reference geometry to act like normal geometry

Easy to implement if you lose all the constraints to the external.

> and back

So the converted geometry should remember its old status. 

What you ask is certainly possible but if you could take a look in the Sketcher code you'd know your dream become reality in a far futur.
What I propose do the job, is quite easy to implement and can come in a few weeks.

**Comment by maxwxyz** [comment]
I'm not a coder unfortunately. So you mean a function to automatically redraw the reference geometry on top of the reference?

**Comment by FlachyJoe** [comment]
> So you mean a function to automatically redraw the reference geometry on top of the reference?

Yes, automagically create normal geometries constrained to the below external. And if you don't need these geometries or their constraints anymore simply delete them, external will be still here.

**Comment by MisterHW** [comment]
The seeming inability to be able to turn external geometry is something that causes me great grief, so forgive me for adding my 2 ct here.

Apparently, stubbornly redrawing the same geometry is a recipe for disaster when it comes to constraints, to the point where I don't really know how to make it work without producing results like the one shown below. Drawing lines and arcs automatically generates constraints (like H, V) which then lead to over-constrained sketches by just tracing what is already there.

![grafik](https://github.com/FreeCAD/FreeCAD/assets/24977335/91631e9b-b3e8-412f-a071-df1f9c1c8a53)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/24977335/2d4c762e-9486-4b82-9108-8edd11892d4b)

![grafik](https://github.com/FreeCAD/FreeCAD/assets/24977335/2d63219d-3fb2-456d-abec-d6b77de4f378)

**Comment by NomAnor** [comment]
I also use this feature (from realthunders branch) quite often to reference geometry from a master or helper sketch. Sometimes even from binders.

I don't know how the sketcher works internally, so I might be complely wrong:
 From the outside a sketch is a bunch of lines (i think the occt term is wire). I would presume that the list of exposed wires (that for example extrude is using) is calculated from an internal list of _normal_ sketch geometry. Than there is an internal list of _construction_ geometry and an internal list of _external_ geometry. Would it be possible to give the external geometries an additional flag wether they should be treated as _normal_ or _construction_. When calculating the wires that are exposed to the outside, additionally include the external geometry that is marked as _normal_.
I'm not sure if the check for full constraint needs to change, because external geometry is always fully constrained by definition so only the list of _normal_ geometry must be checked, which should be the same as it currently is the case. Constraining other geometry to the external geometry would also not change because the flag is irrelevant for that.

Visually the flag should influence the color. 

Reusing the contruction switch button to toggle the flag is in my opinion an intuitive way for the user.

**Comment by kaiwas** [comment]
I understand that working with external geometry until the toponaming problem is fixed is not very relevant, but I would still like to voice it.

1. There is currently no quick way to convert external geometry to base sketch geometry. To solve this problem, you have to outline the external geometry by clicking on all the vertices of the external geometry. Moreover, this procedure is very complicated because it requires excessive precision to hit the vertices.

Maybe it would be possible to make some kind of tool, when you click on it, the line of the external geometry would turn into a base line (probably it would simply automatically create a stroke)? (I tried different options but didn't find a solution)
![Covert](https://github.com/FreeCAD/FreeCAD/assets/32273833/7df0b6fe-0215-42b3-a924-882364649ca6)

2. It seems that external geometry cannot always be created from faces. This can be seen at the initial stage in the attached video. Although, in essence, the selected plane has restrictions, which we can ultimately obtain by clicking on each edge of this face.
There is also no multiple selection of edges using a frame (border select).

https://github.com/FreeCAD/FreeCAD/assets/32273833/d2f8dc52-67cc-4f09-a82d-d8cb471d7b42

**Comment by TomaszSzt** [comment]
Note:
 This functionality is present in "FreeCAD Link" realthunders branch. It _mostly_ works_ as expected. Maybe it is a time to pull it into main branch too? I personally find the realthunders branch to be far more useful for machine design than the main branch so it became my primary tool.

**Comment by PaddleStroke** [comment]
Good to know it's in linkstage so at least we know where to look for to see how to implement it.
Yes linkstage has a lot of cool features and it's sad that most of them didn't made it to master.
Pulling features from RT branch is most of the time not that easy And this one is probably a hard one I would guess.

**Comment by obelisk79** [comment]
With all of this discussion, has anyone done an analysis to better understand how external geometry is handled when sketching in other CAD software? I see some discussion of what the behavior 'should be' without providing examples. 

This isn't some ground-breaking functionality that hasn't already been addressed in commerical CAD. We shouldn't be trying to invent a better toaster here.

**Comment by NomAnor** [comment]
Here are some of my thoughts from a users perspective:

I'm fine with "external geometry" being its own entity in the sketch. This makes its explicit for me that there is a dependency on something else. When needed the external geometry could be created automatically, but I see this as just a UI convinience.

Beside the distinction between internal and external geometry, I would like geometry to be independantly either "normal" ("defining" in LinkMerge) or "construction". Normal geometry is used by other tools and features to create further geometry (e.g. extrude) or just as a reference for other sketches in a master sketch. Whereas construction geometry is a helper to construct the desired shape.

Sometimes construction geometry can also be helpful as reference geometry for features, e.g. rotation axis for revolution. Or as reference in another sketch. I think Fusion360 and Solidworks show construction geometry in the 3D view (dashed lines) and allow to reference it, just as normal geometry. This is useful if you don't want to create a master sketch. But when external geometry can be "normal", using a master sketch might be the better approach.

**Comment by MisterHW** [comment]
It may be beyond the scope of this issue, but I often feel that like svg, sketches could make god use of the concept of layers. 
We could have transformed versions and copies of details as separate layers, and at this point could file external geometry under its own layer without having to think about introducing new categories (linked) to represent the ties to an external origin. External sketches could be pulled in as locked layers. generated layers would also be locked and have their own delegates to change parameters.
Such sketches could automatically be expanded into multiple drawings for documentation, solving the recurring struggle between easy access and "don't put too much into one sketch".

**Comment by TomaszSzt** [comment]
@obelisk79
>(...)With all of this discussion, has anyone done an analysis to better understand how external geometry is handled when sketching in other CAD software? (...)

I was using Autodesk Inventor for about 10 years before I moved some less complex jobs to freecad due to some $$ issues. 

In Inventor software you can project any geometry (edges, points, planes) and you can decide if it is construction or not by switching it back and forth. Projection can be done from part, from assembly, from lines in other sketch and etc. Mainly - from anything you can see. 

The RT branch does almost everything Inventor do with an exception of an ability to project a contour of the surface (wall) of an object. This is something I miss much, because Inventor can nicely deal with updating projection of an entire wall of a solid onto a sketch even when the number of edges and their type changes. How can it deal with later is a completely another part of the story (poor that is).

I would love to use FreeCad for a daily job, primary because of $$ it can save on licensing cost, but for it to be possible one minute of work in Inventor must not take more than two or three. While without a "defining" projected geometry it is a ratio of one minute to one hour or even worse (try to line over a cross section of some nasty shape). The cost of license is then compensated by the cost of work hours spent. RT branch is a life saver in this case.

I am still on steep edge of learning curve with Freecad, so I may be mistaken a lot in my opinions. Feel free to correct me if I am wrong. Unfortunately every 3D CAD is a real pain to learn and there are tones of tips and tricks which are absolutely necessary to know to be able to do any serious work.

@NomAnor  Yes, the inability to project "construction" geometry (non-defining) from sketch to sketch or to even see it in 3D is a pain. Especially because you cannot add much of "defining" geometry without extrusion trying to extrude it too and complain.

**Comment by PaddleStroke** [comment]
After thinking about it for a bit, I think the correct way is to add one line type "defining-external".
This is a medium-large project. I'll have a look at how difficult that would be.

**Comment by FEA-eng** [comment]
> After thinking about it for a bit, I think the correct way is to add one line type "defining-external". So external could be either defining or construction. And user could toggle it back and forth This is a medium-large project. I'll have a look at how difficult that would be.

Any chance to reuse part of the code responsible for that in the Link Branch?

**Comment by PaddleStroke** [comment]
I will check link branch but as they now diverged quite significantly I'm not sure it will be easy to port.
