### ISSUE TITLE
[Feature] Better line separation in depedency graphs (graphviz)

### ISSUE THREAD

**Issue by Geobot19** [FreeCAD/FreeCAD#10207]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Full version info

```shell
[code]
OS: Fedora Linux 38 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.20.2.Unknown
Build type: Unknown
Python 3.11.1, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Alternate_OpenSCAD 1.0.0
  * fasteners 0.4.56
  * Pyramids-and-Polyhedrons
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

Subproject: dependency graph generator
when a dependency graph gets messy, the lines on the graph can get way to close together, making it difficult to follow any one line. Here is a close up of an example:
![Example of problem](https://github.com/FreeCAD/FreeCAD/assets/26663436/7a668c55-3835-4ebe-832d-54d38ab52646)

It would be nice for the sake of readability if these lines were spaced further apart.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
The line(s) generation is handled by graphviz so I'm not sure how much the FreeCAD code can be tweaked to improve this. Firstly can you confirm which version of graphviz you are using. On Linux the command `/usr/bin/dot -V` gives the full version, on Windows I'm guessing the user has to right-click the graphviz.exe and select Properties but I'm guessing at that. At present I've just upgraded to version 8.1 and I've probably only got one model complicated enough to produce this scenario.

**Comment by Syres916** [comment]
I used the same model and saved the dependency graph using version 2.38 and 8.1, see attached. I would suggest 8.1 does produces (slightly) clearer graphs. If this is still not clear enough then all I can suggest is using Inkscape to move the nodes in order to give more clarity.

Version 2.38

![CylinderHead_Part_dot2_38](https://github.com/FreeCAD/FreeCAD/assets/46537884/771ac998-e22c-4546-87ae-7a0b28584666)


Version 8.1

![CylinderHead_Part_dot8_1](https://github.com/FreeCAD/FreeCAD/assets/46537884/7dbb3809-0816-4b2e-bb52-e3cb28cc3d36)

**Comment by luzpaz** [comment]
This is the current snapshot of graphviz in the package ecosystem. At the time of this post there are still many repos that aren't using an up to date stable of graphviz.

<a href="https://repology.org/project/graphviz/versions">
    <img src="https://repology.org/badge/vertical-allrepos/graphviz.svg?columns=3&header=graphviz" alt="Packaging status">
</a>

**Comment by luzpaz** [comment]
@Geobot19 can you install v0.21 (latest stable) and see if it improves ?

**Comment by Geobot19** [comment]
the original example was generated using 0.20.2 on fedora 38, I will try with 0.21.0 on arch soon

**Comment by Geobot19** [comment]
![image](https://github.com/FreeCAD/FreeCAD/assets/26663436/d1ddbbd7-63ff-4936-b504-cd30c8e7dce4)
this screenshot is from arch today, problem persists

**Comment by Geobot19** [comment]
graphviz was installed fresh (it wasn't installed on this pc)

**Comment by Geobot19** [comment]
Arch installation details
[code]
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: makepkg
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.11.3, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.56
  * Pyramids-and-Polyhedrons
  * Alternate_OpenSCAD 1.0.0
[/code]

**Comment by luzpaz** [comment]
Looks like https://archlinux.org/packages/extra/x86_64/freecad/ is running graphviz 8.10 (latest stable). I'm assuming this is the package you have installed @Geobot19  ? If so, that's weird. Can you share a test file ?

**Comment by Geobot19** [comment]
[96 percent simple rev 2.zip](https://github.com/FreeCAD/FreeCAD/files/12364240/96.percent.simple.rev.2.zip)
this is the file I've been using, this file. sorry that it's a complex file, the are in the screenshots is around the spreadsheet

**Comment by Geobot19** [comment]
> I'm assuming this is the package you have installed
yes

**Comment by hasecilu** [comment]
Hi, I have seen his problem from a while ago, I tested this [Digital caliper](https://github.com/FreeCAD/FreeCAD-library/tree/master/Industrial%20Design/Hand%20tools/Measuring%20tools) file on FC 0.20.2, 0.21.1 and 0.22.0dev (34591) with same result: edge overlapping.

I read some docs and it seems that there is an algorithm to avoid overlapping of nodes (boxes) but not for edges (lines) because those are made individually.
The used engine is [dot](https://www.graphviz.org/docs/layouts/dot/)

In the `0.22.0dev` version (need to compile it) is posible to save a `.gv` file, a text file that contains info of the graph, using the `dot` package you can generate a new image (`.ps` file)

This is the generated in FreeCAD
![Mesa_de_centro](https://github.com/FreeCAD/FreeCAD/assets/53124818/36e6762f-c897-4fa9-bb2d-349b53c6f874)

And this the generated with: `dot -Gordering=out -Granksep=2 -Gnodesep=1 -Grankdir=TB -Gsplines=ortho -Nshape=box -Tps Mesa_de_centro.gv -o Mesa_de_centro_opti.ps`
Note that the image is bigger and the space is not really optimized, for instance the `Origins` take a lot of space.
But the main thing is that is possible to change some parameters to enhance the graph, tha main change here is to change the style of the splines.
![Mesa_de_centro_opti](https://github.com/FreeCAD/FreeCAD/assets/53124818/01edaeb6-316e-4999-8415-f33dd42d98d6)

I still need to figure it out what changes are needed in the source code, in: 
https://github.com/FreeCAD/FreeCAD/blame/aa5bea4e2e8089bf00f61075a0860dacda42dc8b/src/App/Graphviz.cpp#L41

the method seems unused but looks like it have a way to change the options, also `void Document::exportGraphviz(std::ostream& out) const` is using defaults?

**Comment by AustinPackard** [comment]
Having a similar issue with the lines between nodes being impossible to trace. Are there any alternative methods for listing dependents of a named constraint?

**Comment by luzpaz** [comment]
@hasecilu do you want to submit a PR that could get a fix rolling for this ?

**Comment by luzpaz** [comment]
> Hi, do you think the solution above is good enough?, I think is not optimal but somewhat better because edges don't overlap.

Yes, if it's better solution then we have... sure make a PR. We'll be trending in the right direction. TIA!
