### ISSUE TITLE
StartWB: `/tmp/FreeCADStartThumbnails*` directories are not removed when FreeCAD terminates

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD#10221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33802 +2 (Git)
Build type: Release
Branch: Meins
Hash: c70ded0ad5c6dadc86d3731aa0233f291b2839fa
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.13
  * Assembly4 0.50.2
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.2.63
  * Silk 0.1.3
  * CurvedShapes 1.0.4
  * DynamicData 2.46.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * ExplodedAssembly
  * A2plus 0.4.60n
  * fasteners 0.4.59
  * Render 2023.2.6
```

### Subproject(s) affected?

None

### Problem description

Whenever FreeCAD starts the `Start` workbench creates a folder in `/tmp`, named `/tmp/FreeCADStartThumbnails⍰⍰⍰⍰⍰⍰⍰`. These never get removed so over time a lot of theses folders pile up in `/tmp`.

The folder should be removed if FreeCAD terminates.

see: https://forum.freecad.org/viewtopic.php?p=697560&sid=c7efd2a32a269cdf1eceb2de29017068

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@yorikvanhavre this is Start WB related

**Comment by xtemp09** [comment]
The `/tmp` directory is managed by OS and is automatically cleaned upon system reboot or on schedule. Might I ask why this should be removed when FreeCAD terminates? Is there a rule?

**Comment by yorikvanhavre** [comment]
The fact that these files are not deleted by FreeCAD is useful as they can then be reused by a later session. But then indeed as discussed in #10414 one should put reusable files not in a temp directory but in a cache directory.

I think once things are clearly separated between disposable files (in temp) and cached files (in cache) then this very question stops being one, as we can let the system do garbage treatment in temp.

**Comment by luzpaz** [comment]
> The fact that these files are not deleted by FreeCAD is useful as they can then be reused by a later session.

Per @berberic2 though '*These never get removed so over time a lot of theses folders pile up in /tmp.*'. I'm not sure FreeCAD is re-utilizing them at all.

**Comment by yorikvanhavre** [comment]
> Per @berberic2 though 'These never get removed so over time a lot of theses folders pile up in /tmp.'. I'm not sure FreeCAD is re-utilizing them at all.

Some are and some aren't. The thumbnails are reused. But they should be moved out of /tmp.

**Comment by yorikvanhavre** [comment]
Indeed that's not optimal at all, it will only work for current session...

**Comment by chennes** [comment]
Switching those thumbnails to use cache instead of tmp seems like low-hanging fruit to me, right, @yorikvanhavre ? Just use  `getUserCachePath()` instead?

**Comment by yorikvanhavre** [comment]
There are several actions needed, because ATM the thumbnails are created with a random filename, that can be used only within that FreeCAD session. We also need to change that to create thumbnails that further sessions of FreeCAD can match back to a given file

- use `getUserCachePath() instead of tmp in https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/StartPage.py#L362
- create a function that creates a unique filename from a file path
- replace all uses of mkstemp in https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/StartPage.py by that function
- search for existing thumbnails before creating a new one

Another easier option is to discard and delete all this after each run... It's not that it takes so much time to rebuild, or that rendering speed is of paramount importance here. Also caching the thumbnails has the problem that we should ideally check the timestamp to know when the file has been changed, and recreate the thumbnail

**Comment by luzpaz** [comment]
Folks please help review #10951
