### ISSUE TITLE
[Problem] The vertex display size in Part Design is tiny on high DPI screens

### ISSUE THREAD

**Issue by Intuos5** [FreeCAD/FreeCAD#10223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * BIM 2021.12.0
  * DynamicData 2.46.0
  * Launcher
  * persistenttoolbars
  * SelectorToolbar
[/code]
```

### Subproject(s) affected?

PartDesign

### Problem description

In the Part Design workbench, unlike the Sketcher workbench, there are no display options to increase the size of an edge or a vertex. By default, vertices are displayed as 1 or 2 pixels, which is barely visible. The same applies to edges. This came up on the Hackathon discussion. 

![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/63149655/353a1ac3-7784-46ac-98c3-c556dcd61098)

The screenshot above is on a 4k screen, Windows 10 with 175% scaling. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
Well, the attendees of the Hackathon must not be daily modellers, the ability to set vertex/point size and edge/line width has been in FreeCAD since at least:

```
OS: Linux Mint 20.3
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4.
Build type: Release
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.3.0
Locale: English/United Kingdom (en_GB)
```
and probably before but I can't prove it at this time. It applies to shapes not just Part Design objects.

![Shape_appearance_VertexSize](https://github.com/FreeCAD/FreeCAD/assets/46537884/6a4f0723-13d7-4ef3-baa1-f83687dc0787)


and can be changed on an individual body/solid:


![Object_PointSize](https://github.com/FreeCAD/FreeCAD/assets/46537884/304ed61f-5e0a-4d7f-9ba4-523c3969abe5)

**Comment by Roy-043** [comment]
Closing...
