### ISSUE TITLE
Start WB: Document info popup not honouring system date locale

### ISSUE THREAD

**Issue by timsoftgit** [FreeCAD/FreeCAD#10793]
if you hover over a document the date information of the file is shown in US format (m/d/yyyy) instead of current locale (British) which is d/m/yyyy
see example which was of a file created 12 september 2023, not 9th December 2023

![freecadsshot](https://github.com/FreeCAD/FreeCAD-Bundle/assets/7967099/b68c7cca-e656-47c6-b2c4-2d81b920ed1e)

this affects windows 0.21.0 release version and also the 10th Sept 2023 weekly build windows version.
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
[/code]

**Comment by luzpaz** [comment]
Please edit the OP and add your full [About](https://wiki.freecad.org/About) info. TIA

**Comment by yorikvanhavre** [comment]
I can confirm this...

In the code it's set correctly:
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/StartPage.py#L95

The problem is that it asks for FreeCAD's 'TimeFormat' preference value:
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/StartPage.py#L91
Which cannot be set anywhere in the Start preferences.

I'd see a couple of possibilities:

1. We add that setting in the start page preferences
2. We stop using that and rely on the system. But how to obtain a default time format string from the system in python? I can't seem to find the right way...

**Comment by luzpaz** [comment]
@yorikvanhavre any idea who would be interested in tackling this ?
@qewer33  ?

**Comment by yorikvanhavre** [comment]
I can do this, but would love some help from Python gurus out there for the best way to convert a timestamp obtained in https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Start/StartPage/StartPage.py#L176 into a format preferred by the system...

**Comment by luzpaz** [comment]
@0penBrain can you weigh-in? TIA

**Comment by 0penBrain** [comment]
> I can do this, but would love some help from Python gurus out there for the best way to convert a timestamp obtained in https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Start/StartPage/StartPage.py#L176 into a format preferred by the system...

Normally just using `'%c'` as time format is enough.
You can test with something like
```
import time
time.strftime("%c")
```

If it doesn't work, please check what `locale.getlocale(locale.LC_TIME)` returns.

**Comment by luzpaz** [comment]
@yorikvanhavre :point_up_2:

**Comment by yorikvanhavre** [comment]
Okay using `%c` seems to do it... Thanks @0penBrain
