### ISSUE TITLE
[Problem] Unable to create chamfer

### ISSUE THREAD

**Issue by gms2009** [FreeCAD/FreeCAD#10960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Unable to create chamfer on edge4 and edge16, just the edges between 2 objects

https://github.com/gms2009/FreeCAD/blob/master/leg301.FCStd

### Full version info

```shell
[code]
OS: Ubuntu 22.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.1.Unknown
Build type: Unknown
Python 3.10.12, Qt 6.2.4, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/United States (en_US)
[/code]


on windows 10 also
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment]
The edges can be chamfered, but the max. chamfer size is 0.399mm. This is related to how the ends of the chamfer curve around to the top of the model where the width is 8mm. If you don't want those endings, or want to use a larger size you will have to change the modeling approach (ad the flange-less portion of the shape after the chamfer, or create the chamfer by sweeping a triangular sketch).

This issue is related to how OCC handles chamfers and fillets there is not much FreeCAD can do.

Before creating a next GitHub issues, please consider consulting the [FreeCAD forum](https://forum.freecad.org) first.

I am closing this.
