### ISSUE TITLE
[Problem] Report view is unreadable because of unsupported font

### ISSUE THREAD

**Issue by mrrcheese** [FreeCAD/FreeCAD#11681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Text in Report view is unreadable. 
![image](https://github.com/FreeCAD/FreeCAD/assets/153240016/cc609536-8e1d-49b9-b071-5975fadf02c3)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.60n
  * fasteners 0.4.56
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
@mrrcheese Edit -> Preferences -> Python -> Editor (tab)
Change the font in the 'Family' text box

**Comment by Syres916** [comment]
@mrrcheese could you please advise the name of the font causing the issue, as previously mentioned it will assist in the improvement of the code.

**Comment by mrrcheese** [comment]
"BC C39 3 to 1 Medium" was the default font when I installed FreeCAD 0.21.1. This is the font that failed.
Variations of the "Code39" fonts failed for some characters.

**Comment by Syres916** [comment]
@mrrcheese it would be extremely helpful if you could run the attached macro in FreeCAD and report back the findings please. I've tried a barcode font on my Linux system and typically it didn't get through the check so I'm struggling to find the unique parameter to exclude them:

```
import FreeCAD as App
import FreeCADGui as Gui
from PySide import QtCore, QtGui

familyNames = QtGui.QFontDatabase().families()
for family in familyNames:
    if QtGui.QFontDatabase().isFixedPitch(family) and QtGui.QFontDatabase().isSmoothlyScalable(family):
        App.Console.PrintWarning("Accept: " + str(family) + "\n")

    if QtGui.QFontDatabase().isFixedPitch(family) and not QtGui.QFontDatabase().isSmoothlyScalable(family):
        App.Console.PrintError("Ignore: " + str(family) + "\n")
```

**Comment by luzpaz** [comment]
CC @mrrcheese :point_up:

**Comment by Syres916** [comment]
Extremely disappointed by the lack of feedback, it seems it'll be easier to have a list of supported fonts for all platforms and only load those that meet the list rather than trying to think of every font that we don't want. I've got to visit a Windows 10 user tomorrow and I'll get my list together (already have a few Linux distros and a Windows 7) but I'll need a Mac user to clarify whether the list includes standard fonts on that platform otherwise this is going nowhere.

**Comment by maxwxyz** [comment]
Is this still relevant?

**Comment by dfcautley** [comment]
FYI
After upgrading to V 0.21.2 the font was a barcode, which is not helpful. It was not that before.
![image](https://github.com/FreeCAD/FreeCAD/assets/115596027/c618b3e5-a56c-4051-b0ce-c4f54a2e83e3)
Per comments above, changing the font family makes the text in the report pane/window readable.

**Comment by maxwxyz** [comment]
Is this still relevant in the dev version?

**Comment by luzpaz** [comment]
cc @mrrcheese https://github.com/FreeCAD/FreeCAD/issues/11681#issuecomment-1854469398

**Comment by kriswilk** [comment]
Not sure what the status of this issue is, but I'd like to report that, using 1.0RC2 in Windows 11 (23H2), the default font family for the Python Editor (and hence the report view) is still the nasty "BarCode". Yes, I deleted all previous settings files in %AppData% for a completely clean startup.

Unless I'm doing something wrong, this should _definitely_ be addressed before 1.0.

![Screenshot 2024-10-06 221931](https://github.com/user-attachments/assets/48e35084-f2bd-44ed-849f-246c5ed770e3)

**Comment by maxwxyz** [comment]
I cannot reproduce myself but label this as blocker to discuss

**Comment by kriswilk** [comment]
It seems that those of us experiencing the issue all have some non-standard fonts installed...often barcodes. In my case, the `BarCode` font was probably installed by my Zebra thermal printer software.

Do I understand correctly that there is an exclusion list built into FreeCAD to prevent certain fonts from being selected? If this is the case...why? A hard-coded list seems like a really fragile solution.

Can't the editor font simply default to something standard, like `Courier New` on Windows or the equivalent on other platforms? Or as a fallback, the standard UI font used everywhere else in the application?

**Comment by Roy-043** [comment]
I have been annoyed by this issue as well. But in my case it is not that severe. I get the BatangChe font, which is still readable.

I think there are some issues with the `getMonospaceFont` function.

I have translated it to Python first as I hardly know C++, and have then tested the Python code on Windows and Linux. So please take the rest of this comment with a grain of salt.

Some finding:
* The family names, "Monospace" and "Courier", must be spelled with a capital. `font.family()` will return the specified family name. Without a capital there is a problem here: https://github.com/FreeCAD/FreeCAD/blob/9dd105b16a4c3317a90608f994906ad29d630331/src/Gui/PreferencePages/DlgSettingsEditor.cpp#L305 https://github.com/FreeCAD/FreeCAD/blob/9dd105b16a4c3317a90608f994906ad29d630331/src/Gui/PreferencePages/DlgSettingsEditor.cpp#L329-L333
* I don't think `font.fixedPitch()` works. I have replaced it with `db.isFixedPitch(font.family())`. This is also used in another part of the C++ code.
* I don't think the lines with `font.setStyleHint()` work.

The Python code finds the Monospace font on Linux and the Courier font on Windows, but this is of course because those families exist on my machine.

Python version:
```python
def getMonospaceFont():
    from PySide import QtGui
    db = QtGui.QFontDatabase()
    font = QtGui.QFont("Monospace")
    if db.isFixedPitch(font.family()):
        print("a")
        return font
    font.setStyleHint(QtGui.QFont.Monospace)
    if db.isFixedPitch(font.family()):
        print("b")
        return font
    font.setStyleHint(QtGui.QFont.TypeWriter)
    if db.isFixedPitch(font.family()):
        print("c")
        return font
    font.setFamily("Courier")
    if db.isFixedPitch(font.family()):
        print("d")
        return font
    return font
```

C++ version:
https://github.com/FreeCAD/FreeCAD/blob/9dd105b16a4c3317a90608f994906ad29d630331/src/Gui/PreferencePages/DlgSettingsEditor.cpp#L60-L78

**Comment by Roy-043** [comment]
Using `isSmoothlyScalable` may not be reliable:
```python
>>> db = QtGui.QFontDatabase()
>>> db.isSmoothlyScalable("Courier")
False
>>> db.isSmoothlyScalable("Courier New")
True
>>> db.isSmoothlyScalable("Libre Barcode 128")
True
```

**Comment by Roy-043** [comment]
To clarify the original problem:
The issue does not occur with a fresh install (without a CFG file). It is only after editing a preference (any preference) that, because the default font family is not found in the font list, the first font in the list is used instead.

I think the `getMonospaceFont` function can be as simple as the Python version below. This function will always return a correct family name. We can therefore expect it to be found in the `fixedFamilyNames` list. That list will still contain barcode fonts, but that is less of an issue IMO.

```python
# Ubuntu: DejaVu Sans Mono
# WIndows: Courier New
def getMonospaceFont():
    from PySide import QtGui
    font = QtGui.QFont()
    font.setStyleHint(QtGui.QFont.Monospace)
    font.setFamily(font.defaultFamily())
    return font
```

**Comment by kriswilk** [comment]
Qt's built-in function `QFontDatabase::systemFont()` _"returns the most adequate font for a given type case for proper integration with the system's look and feel"_. It is designed for this situation:

https://doc.qt.io/qt-5/qfontdatabase.html#systemFont

Using it, FreeCAD's `getMonospaceFont()` can be reduced to:

```cpp
QFont getMonospaceFont()
{
    return QFontDatabase::systemFont(QFontDatabase::FixedFont)
}
```

I submitted this patch as PR #17275. I've compiled and tested it against Qt 6 on Windows 11, confirming that it resolves the issue. On my system (which was affected by the issue), the default font is correctly set to `Courier New`.

Perhaps someone can try compiling against Qt 5, and on other platforms?
