### ISSUE TITLE
[Assembly] Card 11 :  Assembly wb could work with App::Part to enable static assemblies

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#11708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

App::Part are designed to be ‘static assemblies’. ie assemblies where things do not move. But doing so requires the user to place components manually. Which is probably difficult with only the Transform tool. So it requires additional addons like manipulator I would guess.

We could make it possible to use the assembly workbench on App::Part. Like so :

If an app::part is active (and not a assemblyObject) then only the Fixed joint tool is active.

Using the Fixed Joint tool in this circumstance would not create joint object. Only position the solids as the joint would dictate. The second part moving to match the first JCS.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment]
What would be the default behavior when adding bodies to a part? Their origins are coincident?

Because it seems FreeCAD will follow the Catia way, I would like to describe a use case that I encountered very often in my career. Basically, in Catia bodies do not have an origin so it’s pretty much like all the bodies are at the origin and cannot move. Sketch, lines, surfaces, etc. that are in a geometrical set at the part level are used by the different bodies to build different zones of the part. It can be sheetmetal that are eventually welded (and thus the object is one part) or simple objects (primitive-like) to be used in boolean operation, pretty much like with the Part workbench. Bodies are also often used for deformable objects like o-rings: because they can have a different shape in different situations (piston, lid, belt, etc.), it is modeled as a body and it is only added in the PDM.

What Catia dosen’t do, though, is allowing a different material for each body. Is it going to be possible with FreeCAD. (This is likely out of scope of the issue.)
