### ISSUE TITLE
[Problem] V0.22 Sketcher_Rotate clones chord dimension as equal constraint

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#12034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sketcher_Rotate clones a chord dimension (Sketcher_ConstrainDistance) as Sketcher_ConstrainEqual constraint.

1. Open [sketch-rotate-clone-chord-dim.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/13980181/sketch-rotate-clone-chord-dim.FCStd.zip) (remove the zip extension).
2. Open the sketch.
3. Select the arc.
4. Call Sketcher_Rotate.
5. Check "Clone Constraints".
6. Change number of copies to 2 or more.
7. Finish the command in the usual manner.
8. Result: copied arcs have a Sketcher_ConstrainEqual constraint.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35594 (Git)
Build type: Release
Branch: main
Hash: 49e7bba9c7390b11e6cc9acebd10cc1568ec8869
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Ok so it appears that the problem is that I reversed the situation. ie the tool replace with equality when 'Clone constraint' checked. Which is the reverse of what the tooltip says.

I suggest renaming the checkbox 'Replace dimensions by equalities' which is much more meaningful than current 'CLone constraint'. And updating the tooltip.
