### ISSUE TITLE
[Problem] PartDesign_addaptivHelix does not work with circle sketches

### ISSUE THREAD

**Issue by Lowrider39** [FreeCAD/FreeCAD#12185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I draw a sketch with for example an rectangle. With this sketch I want to make a helix. This works very well. When I use instate of the rectangle a circle to produce a wounded wire, the helix is completely distorted like you use the wrong algorythm for shaping.

### Full version info

```shell
OS: openSUSE Leap 15.5 (KDE//usr/share/xsessions/plasma5)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35735 (Git) AppImage
Build type: Release
Branch: main
Hash: c12a5c2a163c1a277cf273106899209792be152d
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * freecad.gears 1.2.0
```
```


### Subproject(s) affected?

None

### Anything else?

![circle_helix_distorted](https://github.com/FreeCAD/FreeCAD/assets/51019803/968132ea-9a15-44f0-9cf3-5238b13e3c96)
![circle_sketch](https://github.com/FreeCAD/FreeCAD/assets/51019803/1619905a-4c1a-44fb-8f4a-9b81803d070c)
![Rectangle_Helix_ok](https://github.com/FreeCAD/FreeCAD/assets/51019803/31f6429e-3ff6-4c79-a311-147815287699)
![rectangle_sketch](https://github.com/FreeCAD/FreeCAD/assets/51019803/402a4384-c74e-4c63-9ba8-a48b94654680)
![helix_parameter](https://github.com/FreeCAD/FreeCAD/assets/51019803/e4de359f-d0f0-476e-bb97-7018beaf51a1)


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
1. I wouldn't say that it doesn't work. It's just an old known display issue. If you e.g. export the model as a STEP file and import it to another software, it will be fine. So the geometry is created properly.
2. There were some fixes in this regard. The last one is this: #12977
3. You could try decreasing the maximum deviation and angular deflection in the shape view settings if the issue is still there. It works for me:

![helix](https://github.com/FreeCAD/FreeCAD/assets/59876896/d87da407-68d4-4b4a-99f9-1fdea6a05e8c)

But even with the default settings, it's not that bad, just less detailed:

![helix 2](https://github.com/FreeCAD/FreeCAD/assets/59876896/d5753dfc-c457-4ceb-862b-42d210375920)

4. It would be better if you could share the images directly here next time.
