### ISSUE TITLE
[Crash] Variable Link causes SIGSEGV in _LinkBaseExtension::extensionExecute()_

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#12281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

With the file below, setting **Caisson001.LinkCopyOnChange** to **Tracking** causes a segmentation error at L330
https://github.com/FreeCAD/FreeCAD/blob/0dcfe945053e0fc5c0502f4fc13d2fcd18ebaea2/src/App/Link.cpp#L322-L332

It seems `linked` doesn't point to a valid **DocumentObject**
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/5d222acd-0527-484c-a56a-23e758fa3ea2)

Ping @realthunder 

### Full version info

```shell
OS: Debian GNU/Linux trixie/sid (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35823 (Git)
Build type: Release
Branch: main
Hash: 087263547dedb4d58ee31a54d96b8db1509eb44f
Python 3.11.7, Qt 5.15.10, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Core

### Anything else?

Steps to reproduce:

1. Open  [VariableLink_CrashTest.zip](https://github.com/FreeCAD/FreeCAD/files/14191690/VariableLink_CrashTest.zip)
2. Set the **LinkCopyOnChange** property of **Caisson001** object to **Tracking**
3. Recompute twice (because of hidden references some objects are still touched after the first)
4. FreeCAD crash

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
It's a typical heap-use-after-free crash.

Inside `LinkBaseExtension::extensionExecute()` there is the pointer `linked` and it's checked whether it's null. The call of `syncCopyOnChange()` removes and deletes many objects -- including the object `linked` points to. So, at this time it has become a dangling pointer. Since it's used further down it causes undefined behaviour and usually leads to a crash.

A fix would be to replace 
`DocumentObject* linked = getTrueLinkedObject(true);`
with
`App::WeakPtrT<DocumentObject> linked(getTrueLinkedObject(true));`
and do the necessary changes. After the call of `syncCopyOnChange()` it must be re-checked if the object is still valid.
