### ISSUE TITLE
[Problem] webengine is a massive dependency that provides little value but gives lots of problems

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD#12505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

as we had discussed at Brussels qt webengine is a pretty big dependency that brings in a lot of problems but there's no real reason why we would need it. It is also one of the roadblocks for [migrating the conda builds to qt6](https://github.com/conda-forge/freecad-feedstock/pull/117) and is not even supported in some hardware architectures (this is relevant for [debian packaging](https://salsa.debian.org/science-team/freecad/-/blob/696f07a826c4eb131598f1afaa5c91ff97fcc56e/debian/rules#L14-20)).

### Full version info

```shell
0.22.0.36012
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

It would be best if we could remove this dependency however right now it's still in use in startpage and the web wb, we can rewrite starpage using just qt widgets or qml if we want to experiment and the web wb is of very little use so it's likely safe to remove. Once we've done this we can finally remove webengine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
+1 to removing the web wb.  There is no reason for a CAD system to have its own browser.

**Comment by yorikvanhavre** [comment]
Indeed the only advantage I can envision (the easy management of downloading CAD files) can much more easily be done outside FreeCAD (for ex by having FreeCAD handle downloaded .FCStd or other CAD files). And what historically was a good idea (you would get easy access to some online libraries and repositories) turns out today to be actually a more complicated access, given the logins, sessions, cookies management etc which FreeCAD is not set up to have.

The main (only?) user of the Web WB is indeed the Start WB. So this means we need a complete rewrite of the start WB. This indeed could be a nice opportunity to experiment with QML.

The Help module also relies on it, but that's optional and it's just an option to kill. This will need some thorough testing, though.

There are still here and there rare workbenches I think that use the web WB. I think one would need to run a search against all the addons (builtin + external). I believe most should be very simple to solve by redirecting to the desktop browser.

**Comment by Roy-043** [comment]
Doesn't the Help function also rely on this?

**Comment by chennes** [comment]
For the Addon Manager (where I've already removed QWebEngine) I display a stripped-down version of the Wiki pages. There's been some work towards migrating to a Markdown-based documentation system, which would help a lot here (Qt 5.15 and later natively support Markdown rendering).

**Comment by Andrei-Pozolotin** [comment]
also https://github.com/FreeCAD/FreeCAD/issues/11553

**Comment by yorikvanhavre** [comment]
Ultimately the plan is to migrate away from the wiki to something more reliable like markdown files. Blender is doing the same thing... But this might still take a long time. As @Roy-043 says there is still a long way to go.

In any case, the Help module also uses its own pyside-qwebengine-based widget (buggy ATM, I need to fix it) to display the doc. So once that is fully working (I'm writing some unit tests for it now), that means it does not depend on FreeCAD's web module anymore.

**Comment by yorikvanhavre** [comment]
So there is a series of actions to take here, probably each would need a separate issue:

* [ ] Rebuild the Start WB without web/HTML (qt only)
* [ ] Free the Help WB from the Web WB dependency (and provide a fallback if no pyside-webengine available)
* [ ] Work further on the wiki -> markdown migration (GSoC project maybe?)
* [ ] Verify dependencies of other workbenches (built-in and addons) on the Web WB

**Comment by pierreporte** [comment]
Qt has a help framework but I can’t determine if in depends on Qt WebEngine. It can read HTML files so what will be generated by the wiki replacement could easily be integrated in it. Or, more simply, it should open the web browser to a local or remote URL.

**Comment by yorikvanhavre** [comment]
We used the Qt help framework before... But it is a major PITA because it requires your whole documentation to be packed into huge binary files and has VERY BAD support of HTML, which gave enormous problems, never looked good, made the FreeCAD sources gigantic (they still are, because of that cursed history) and were extremely cumbersome to use and search...

So we ditched it all and started the Help module which (for now) just accesses the online documentation and that's it. But the ultimate goal is to have our doc as a clean repo of markdown files, that can also be cloned/downloaded for offline use, and have in FreeCAD a good and simple viewer to read those files.

**Comment by sliptonic** [comment]
Fixed by #13134
