### ISSUE TITLE
[Problem] Task panel Close button does not work consistently with Sketcher_CreateRegularPolygon

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#13042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

If the Sketcher_CreateRegularPolygon tool (or any of the other polygon tools) is running and no input has been provide, the Close button in the task panel does not work. This does not happen with other geometry creation tools.

1. Start a new sketch.
2. Call Sketcher_CreateRegularPolygon.
3. Press the Close button.
4. Result: does not work.
5. Start another tool, for example Sketcher_CreateLine.
6. Press the Close button.
7. Result: Task panel closes.

### Full version info

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
I don't get it. Starting the Regular polygon tool makes a small window with "Number of sides" pop up. Then you can't click Close in the task panel because the focus is on that small window. In fact, you can't click anything else than Ok or Cancel there. I would say it's normal. After confirming (or when using other polygon tools), you need to draw the polygon and then the Close button works normally. Is that right?

**Comment by Roy-043** [comment]
I can't reproduce with the version listed below. This has apparently been fixed.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
```
