### ISSUE TITLE
Assembly: Dragging objects

### ISSUE THREAD

**Issue by FreeCutter** [FreeCAD/FreeCAD#13058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Enclosed file includes two example bodies to be dragged.

**Repro:**
1. Assembly activated by double-click
2. Click on any surface of first body (e.g. of hexagon-bar) to get it selected 
3. Positioning mouse pointer above any surface of second object (e.g. quad-bar), that face turns yellow
4. Click-dragging with mouse 

**Expected result:**
- Selected face of first body gets deselected
- Second body is moved while click-dragging

**Actual result:**
- First body is moved while click-dragging

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * fasteners 0.5.14
  * SelectorToolbar
```

### Subproject(s) affected?

Assembly

### Anything else?

[Test dragging bodies.zip](https://github.com/FreeCAD/FreeCAD/files/14668795/Test.dragging.bodies.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Can reproduce. It also happens when the last feature of a body is selected but not if the body is selected itself.
Same principle which is annoying in 
- https://github.com/FreeCAD/FreeCAD/issues/12486
- https://github.com/FreeCAD/FreeCAD/issues/11132
- https://github.com/FreeCAD/FreeCAD/issues/11353#issuecomment-1807046345

Either there should be a general selection fix, outside of PD only select the entire body. Inside PD, hopefully after TNP solving select the feature that created the selection, not always the last (like in RT branch). https://github.com/FreeCAD/FreeCAD/issues/11429
