### ISSUE TITLE
[Suggestion] Add Annotation editor current line color to colors settings

### ISSUE THREAD

**Issue by willrabbermann** [FreeCAD/FreeCAD#13201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can barely read the annotation current line. As far as I know its color setting is not located in Preferences->Tech Draw->Colors.

![Screenshot from 2024-03-28 10-25-04](https://github.com/FreeCAD/FreeCAD/assets/105755092/a570cdaf-6905-4ebe-9934-8b228e02816d)

### Full version info

```shell
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.63
  * Assembly4 0.50.7
  * fasteners 0.5.12
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please provide full about info.
Are you using a theme?

**Comment by willrabbermann** [comment]
Default theme. Is that where its set?

**Comment by maxwxyz** [comment]
@MisterMakerNL FYI

**Comment by MisterMakerNL** [comment]
This is an oldy, I think we even updated the text input window to get this
fixed. But I'm 95% sure it's fixed in 0.22.

Op donderdag 28 maart 2024 schreef Max Wilfinger ***@***.***>:
> @MisterMakerNL FYI
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NbUp1hF1rxxu0ypqckEzrGnRN5W6AkA4WaBbfDF1jTXjfdN2TRNhQ3w0af57TdJfnLP8WZfOOq8XXI5X404F_4WqfQbim_2pvNZz4_ebJOYBWrPaVIeL7gLbo0hv0XsFfXQU9B7o3DVHoR5kCL0A63bRVt2TxKnm0LhRPCXYd788egvdXYi5hWBn1Lnu1OJ7gd8hvAsYmxpL6-8txrr8MR0_bLPn2Sb1L-kKlhiOJKN0Q-yynN_WeE=s0-d-e1-ft#https://github.com/notifications/beacon/AHDMTIVIDJGB6LZQY4ZPIRLY2RA2LA5CNFSM6AAAAABFM74F2SWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTYX2RFO.gif>Message
ID: ***@***.***>

-- 

Met vriendelijke groet,
Marijn van den Heuvel

**Comment by maxwxyz** [comment]
@willrabbermann could you please try this in the current weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by maxwxyz** [comment]
Already implemented

**Comment by willrabbermann** [comment]
![Screenshot from 2024-03-29 05-11-40](https://github.com/FreeCAD/FreeCAD/assets/105755092/e88b1250-8611-4aaa-a02c-28d56b7ccdcb)
Should I be using the rich text editor instead, its editor looks better.

**Comment by maxwxyz** [comment]
Depends on your use case.

**Comment by willrabbermann** [comment]
The problem is still under the ProDark theme. That was the one I had selected.
Other themes appear fine.
![Screenshot from 2024-03-29 12-21-01](https://github.com/FreeCAD/FreeCAD/assets/105755092/bf3046be-3a32-4c54-8206-2670aa6ea676)
![Screenshot from 2024-03-29 12-21-15](https://github.com/FreeCAD/FreeCAD/assets/105755092/ba7c09cc-5932-424c-86d1-f12ea18e99fc)
