### ISSUE TITLE
[Problem] Invalid SubElementNames

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#13248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Newly created Draft_Clones have invalid SubElementNames. Saving and reopening the file fixes this. This is a regression, the problem does not occur in V0.21.

I think this is a problem in Core, not in the Draft Workbench.

1. Create a Part_Box.
2. Make it invisible.
3. Create a Draft_Clone from it.
4. Select a face of the clone.
5. Paste `FreeCADGui.Selection.getSelectionEx("", 0)[0].SubElementNames` in the Python console.
6. Result is something like: `(';Face3;:Hae1,F.Face3',)`. It should be: `('Face3',)`.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36596 (Git)
Build type: Release
Branch: main
Hash: 380d452adb5da85f47543a316b6b533f84e829c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
> Result is something like: (';Face3;:Hae1,F.Face3',). It should be: ('Face3',).

Looks like some Topo Naming code is active. The method SelectionSingleton::checkSelection() gets as input "Face3" but then sets the sub-name of the `_SelObj` to that cryptic name.

**Comment by CalligaroV** [comment]
Hi @Roy-043 and @wwmayer!

I gave a look at this issue and yes, it's related to some modifications introduced for TNP.

For now I found a fix (probably temporary) that should solve both this issue and #13009 .
The full fix is more complicated and needs to import more code from RT fork, I already started working on that.

Regardless for that, I opened #13297 that contains the temporary fix.
Can you try it? On my local build it works.

TIA!

**Comment by Roy-043** [comment]
This issue is back. See #14196.

**Comment by Roy-043** [comment]
Additional finding:
Highlighting of multiple selected subelements of the clone does not work properly. Only the first subelement is highlighted.

**Comment by bgbsww** [comment]
That sounds very familiar ...  #14699 may fix this.

**Comment by Roy-043** [comment]
I have to reopen again. This is still an issue. Can somebody please add a unit test for this? Something like this:
```python
def are_subelementnames_ok():
    
    import FreeCAD as App
    import FreeCADGui as Gui
    import Part
    
    doc = App.ActiveDocument
    plane = doc.addObject("Part::Plane", "Plane")
    plane.Length = 10
    plane.Width = 10
    extrude = doc.addObject("Part::Extrusion", "Extrude")
    extrude.Base = plane
    extrude.LengthFwd = 10
    doc.recompute()
    
    Gui.Selection.addSelection("", extrude.Name, "Face2", 5, 0, 5)
    
    return FreeCADGui.Selection.getSelectionEx("", 0)[0].SubElementNames == "('Face2',)"
```

**Comment by bgbsww** [comment]
The proposed test is unfortunately not correct.  On a working LS3, the selection ( correctly ) includes an element history path:

```
>>> are_subelementnames_ok()
False
>>> FreeCADGui.Selection.getSelectionEx("", 0)[0].SubElementNames
(';Edge2;:G;XTR;:He13:7,F.Face2',)
>>> 
```

The selection issues should be fixed by correctly handling the full element names ( fix for #14897 on the way).  Is there another example you are seeing?

**Comment by Roy-043** [comment]
How can it possibly be that the subelement names are different after saving and reopening? And what does that mean for the TNP solution?

**Comment by bgbsww** [comment]
They aren't different.  Or if they are, that's a problem.  They are more complete.  Note that Face2 becomes ;Edge2;:G;XTR;:He13:7,F.Face2   and that is properly processed into Face2 using that last period seperator when required.

**Comment by Roy-043** [comment]
Well, sorry to have to say this, but after saving and reopening a file with a Part_Extrude or a Draft_Clone, subelement names are different.

After creating the extrude:
`FreeCADGui.Selection.getSelectionEx("", 0)[0].SubElementNames => (';Edge2;:G;XTR;:H30c:7,F.Face2',)`

After saving and reopening:
`FreeCADGui.Selection.getSelectionEx("", 0)[0].SubElementNames => ('Face2',)`

**Comment by bgbsww** [comment]
So, again, I wouldn't describe those as different.  Yes, obviously the text is, but what I'm reading is Part_Extrude and Draft_Clone elements are failing to correctly save and restore their elementMaps.  Which is absolutely true, because there's a massive save-and-restore problem I'm still working to get my arms around.  Biggest bug on my plate.  It's still the same subelement though - if the end part after the '.' matches, then it is the same - and could be regenerated, but that's not what we should do.

Thank-you though for the persistence.  You are correct that there is an error here to be addressed; it just isn't that the names are changing - it's that they are incomplete after a reload with a missing path.

Cases where it goes from Face2 to Face4 ( or ANYTHING;YOU-WANT-HG65123,Face4 ) - that's changing, indicative of an actual toponaming detection failure, and a more severe, though generally exact case specific problem.

**Comment by bgbsww** [comment]
#14898 addresses saving and reloading and hopefully the consistency issue here.  #14699 addressed the selection error.

There is a remaining question of whether or not python .SubElementNames should return mapped ( full history ) or unmapped ( short ) names.  I can make arguments in both directions.

Less (python module or addon) code is likely to break (not respect TNP mitigations) returning the mapped names, as it is the equivalent reference that the software expects.  It would be more intuitive and prettier to return only the short names, but it this case we'd need to make sure that every python place that accepts a subelementname is properly converting back to the mapped name.  I think this is well covered, but it could be a problem.

Since LS3 returns them in mapped form, I'm defaulting to doing the same unless an argument other than pure aesthetics shows up.

Is there a remaining bug here to be addressed?

**Comment by Roy-043** [comment]
Thanks for explaining. I'll close this one.
