### ISSUE TITLE
CAM: Spindle pause for spin up

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

From the FreeCAD Day 2024 Complaint Session:
**When I export everything for my CNC machine there isn't a pause to allow my spindle to spin up to speed. I add this to the gcode manually.**
Discussion:
When I export everything for my CNC machine to mill everything out, there isn't a pause after speeding up. The spindle will wait until it's up to speed. I always need to add this to the gcode manualle. There's no way when creating a toolpath to insert a pause of current events, like: after setting the spindle speed, just wait.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git)
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.10
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.16
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * OpticsWorkbench 1.0.15
  * sheetmetal 0.4.11
```

### Subproject(s) affected?

CAM/Path

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
Pausing for spindle spin-up is highly machine specific.  Some machines detect spindle speed and will automatically wait.  others need manual delay.  

For manual delay it is quite possible with current functionality.

For example, add a Custom to the beginning of the job.  add a G04 P<n> where n is the number of seconds to pause.

The same gcode can be added to the toolchange block of the postprocessor to make it automatic on every toolchange. 

Closing this since current functionality meets the need.
