### ISSUE TITLE
Preferences: Help Button does nothing / Remove it?

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

What is the help button in the preferences supposed to do? Clicking it does nothing but changing the cursor.

https://github.com/FreeCAD/FreeCAD/assets/6246609/7097f934-c043-4cfc-9c81-cafe8404d198

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37063 (Git)
Build type: Release
Branch: main
Hash: 680792030fd664c94829e2c1b78b21788e8d9879
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CfdOF 1.25.11
  * Curves 0.6.35
  * dodo 1.0.1
  * fasteners 0.5.20
  * fcVM-WB
  * freecad.gears 1.2.0
  * OpenTheme 2024.4.20
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
This button is supposed to use the Help module (the same as Help --> What's This? outside of Preferences, leading directly to proper documentation pages). But it doesn't work in Preferences, even in 0.21.2 (and the Help module has been merged since then: #11008). It even crashes FreeCAD on Ubuntu for me. Thus, I submitted a PR removing this button: #14695

Perhaps in the future, the Help module will be extended to work in Preferences as well but it should be removed as non-functional for 1.0.
