### ISSUE TITLE
Stylesheets: Light theme could have better 3D viewport background

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#15749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, the background of the 3D viewport with the Light theme is just pure white and doesn't look so good next to all the widgets/panels. I would suggest adding a small gradient and using a slightly different color there. Maybe a little bit of gray or blue...

![light background](https://github.com/user-attachments/assets/27197f1a-022c-4597-9700-4cd5549d3b82)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment]
I don't think this is a good idea, small gradients don't work because the viewport has severe issues with color-banding. I have played a lot with these settings untill coming up with just white. 
Further more the other whites are almost completely white, which doesn't give much options. 
But you can play around with the settings.
Or if anyone has a more concrete solutions?
