### ISSUE TITLE
C++ DXF importer complains about group code 999

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#16131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

DXF files created by applications other than AutoCAD often have a group code 999 entry. In fact the FreeCAD C++ DXF exporter includes this entry in the files it creates. GC 999 is a legitimate group code used to indicate that the line following it is a comment string.
```
999
FreeCAD v0.22 38553 (Git)
```
The C++ DXF importer issues a warning when reading such a file. IMO this should be avoided. It can only confuse the end user.

Example file (remove the txt extension):
[Circle_cpp.dxf.txt](https://github.com/user-attachments/files/16797236/Circle_cpp.dxf.txt)

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
It should be pretty easy to add a case, I think around line https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Import/App/dxf/dxf.cpp#L2373 that skips data reading if "999" is encountered...

I can try that after 1.0 is out, or maybe @kpemartin ? :innocent:

**Comment by kpemartin** [comment]
The DXF documentation seems to imply these can be placed anywhere in the sequence of records, that is, they are not part of the formal "syntax" of the DXF being divided into sections which in turn each have their own structure.

As such this is probably the best way to handle these, somewhat in the way comments in C are handled at the lexical analysis stage because they can appear between any two tokens in the source, regardless of syntax rules.

I'll fix this as soon as I can get my dev environment up to speed after a year's disuse.

**Comment by yorikvanhavre** [comment]
Thanks!!

**Comment by kpemartin** [comment]
I think I have a fix for this but I'm running into other problems trying to test it.

In particular no entities are imported (even without my changes). A call to `Type::ImportModule("Part::Feature")` fails (`loadModuleSet` is empty and the module fails to load), eventually causing the drawing entity to be discarded.

Poking around in FreeCAD's Python console:
```
doc = ActiveDocument()
obj = doc.AddObject("Part::Feature", "xxx")
```
calls the same `Document::addObject` method, which goes through the same `ImportModule` and succeeds.

Once that's done the Part module is in `loadModuleSet` and the importer gets its entities created properly.

I don't know if this is due to a defective build (I've just made my build environment etc. fresh so this is not a case of it working previously and mysteriously failing) but it also sounds like a side issue of #16068.

I'm going to look into why the module load works when invoked from the python console but not from the importer.

**Comment by kpemartin** [comment]
Hmm, looks like I have to get the Python source to dig further into this.

**Comment by kpemartin** [comment]
I'm kind of stumped. I tried tracing into the `ImportModule` call and got completely lost in the tangle of code that ultimately tries to actually find and import the module, and I can't find said code in the Python source to just plant a breakpoint there. I became completely lost in some sort of byte-code interpreter so perhaps I'm actually in python code (I seem to have a choice of native debugging or Python debugging but not both together, but I'd still have to find the python source code I want to breakpoint)
