### ISSUE TITLE
VarSet: Mismatch in undoing among VarSet dialogs

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#17486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Since VarSet dialogs are non-modal, it is possible to open more than one of them. However, the transactions for undoing are not taking that into account. To reproduce:

1. Open a new file
2. Create a VarSet with `Std_VarSet`
3. Type 'a' for name and press Tab to create the variable
4. Without closing the dialog, create another VarSet with `Std_VarSet`
5. Create a property 'b' in the same way without closing the dialog
6. Click on `VarSet001` to show it in the property view
6. Move to the dialog for `Unnamed#VarSet`
7. Press "Cancel"
8. This removes property 'b' from `VarSet001` instead of removing `a` from `VarSet`.

### Full version info

```shell
OS: Arch Linux (xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39054 (Git)
Build type: Release
Branch: main
Hash: 499d192393d6ba71a7b04b0a0813a2c4789126c6
Python 3.12.7, Qt 6.7.3, Coin 4.0.3, Vtk , OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * OpenTheme 2024.5.16
  * osh-autodoc-workbench 0.2.3
  * Ondsel-Lens 2024.10.21.01
  * fasteners 0.5.29
```

### Subproject(s) affected?

Core

### Anything else?

Related to #17475.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wwmayer** [comment]
This is not the way how the transactions work. 
At a certain point of time there can only exist one pending transaction but not multiple instances.
If there is a pending transaction it will be added to the undo stack as soon as the transaction is committed or a new transaction is opened. If the pending transaction is aborted all recorded changes will be reverted and the transaction deleted.

In your case a transaction is opened for the first dialog. When opening a second dialog then a new transaction will be opened which as said above automatically commits the first transaction. If you cancel the first dialog the pending transaction is aborted but it doesn't know in which context this happens.

So, to fix the issue you must forbid to open several instances of the dialog which anyway is confusing behaviour because a user doesn't really know which dialog created which VarObj instance.
