### ISSUE TITLE
Geometry check does not show any info (like its Name/Label) about the object being checked when the check passes

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#17545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Se, a single oibject what checked but what is it?
![image](https://github.com/user-attachments/assets/8bc202d5-ac1a-49ab-b988-f4e1eedc6ed6)

If something faills, it shows me something at least to know what was analyzed.
![image](https://github.com/user-attachments/assets/f93f00bb-6abd-43ab-bb6a-d9e00ad715ae)

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git) AppImage
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * diff-tools 0.1.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.9
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AIRCAP** [comment]
Let's upscale this issue and also add

- More human readable error messages when the geometry check does NOT pass?

- When one clicks on a failing edge, it is hiughlighted with a white bounding box. This is useless if the error is "edge too short" because the box is typically too small to be visible and/or hidden by geometry - this needs a crosshair

- by the way, sometimes the boundingbox is outright wrong (especially when the geometry has departed euclidean space )
