### ISSUE TITLE
FEM: GMSH mesher - Mesher warnings are not displayed

### ISSUE THREAD

**Issue by AIRCAP** [FreeCAD/FreeCAD#17594]
Making a new issue for that

> @marioalexis84 I think your commit https://github.com/FreeCAD/FreeCAD/commit/cabfbb749fdf5ad822c690a095e62388d9395a2d introduced another "regression" - when you create the mesh, there is a lot less information printed - it just says "success" if the mesher succeeded somehow, mesher warnings are no longer printed. is that on purpose? (typically when teh mesh has negative jacobians thats already reported by gmsh as a warning)

_Originally posted by @AIRCAP in https://github.com/FreeCAD/FreeCAD/issues/17575#issuecomment-2450035998_

**Comment by AIRCAP** [comment]
weird thing - if the FEM analysis is NOT activated, the warnings are printed when a mesh is created - is there a different code path used?

**Comment by FEA-eng** [comment]
If negative jacobian warnings are gone, it's a pretty bad regression. Hopefully, easy to fix though.

@marioalexis84 FYI

**Comment by marioalexis84** [comment]
I'm working on this.

**Comment by FEA-eng** [comment]
@maxwxyz From my perspective, this could be a blocker considering how common negative jacobian issues are and how hard it is now to detect them with this regression.

**Comment by AIRCAP** [comment]
well calculix will tell you "negative jacobian" when you do the actual analysis
also the warnings by gmsh were a bit overwhelming sometimes, with a lot of ignorable warnings that were equally "red" - the one that jacobians are negative at the end often wasn't even visible (scrolled out the right) - so this needs testing and improvement anyway. maybe the user doesn't need to see all the warning, but definitely the one about negative jacobians...  which in practice i usually get rid of by making the mesh finer (reduce maximum cell size)

**Comment by FEA-eng** [comment]
> well calculix will tell you "negative jacobian" when you do the actual analysis 

Yes, but it would be better to know that before running an analysis so that one can quickly remesh to correct this without having to set up the whole analysis, write the input file (which as you know may take a while) and submit it. Also, CalculiX and other solvers may have different checks than Gmsh.

> maybe the user doesn't need to see all the warning, but definitely the one about negative jacobians... which in practice i usually get rid of by making the mesh finer (reduce maximum cell size)

Some Gmsh warnings might be redundant, proper coloring could make it more clear. The ones about element quality are pretty important. And negative jacobian issues are very often reported on the forum, in many cases due to problematic geometry and refinement is not always enough. The Second Order Linear option usually helps but for some geometries it may not be enough either.

All in all, I would prefer all warnings as before for 1.0 and then it could be reduced/improved in the subsequent releases.

**Comment by maxwxyz** [comment]
I'd not consider this issue blocking a 1.0 release it all other blockers are resolved. If possible, a fix before 1.0 in a few weeks would be great though.
