### ISSUE TITLE
严重性 代码 说明 项目 文件 行 禁止显示状态 详细信息错误 LNK2001 无法解析的外部符号 __imp__Py_INCREF_IncRefTotal Mesh D:\code\CAD\newestcode\Build\src\Mod\Mesh\App\MeshFeature.obj 1 

### ISSUE THREAD

**Issue by jsonzsh** [FreeCAD/FreeCAD#17746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

严重性 代码 说明 项目 文件 行 禁止显示状态 详细信息错误 LNK2001 无法解析的外部符号 __imp__Py_INCREF_IncRefTotal Mesh D:\code\CAD\newestcode\Build\src\Mod\Mesh\App\MeshFeature.obj 1 

### Full version info

```shell
newest version
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please check out how to [report issues](https://github.com/FreeCAD/FreeCAD?tab=readme-ov-file#reporting-issues) which could help us diagnose and fix it.

- Test if the issue is still present in the dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
- add full [About](https://wiki.freecad.org/About) info to the issue (`Help > About FreeCAD > Copy to clipboard`).
- share an example file with the issue present. You can upload a zipped file to the original issue.
- add steps to reproduce the issue. Ideally, provide a macro of the issue: `Macro > Macro recording...` and repeat all steps until the issue occurs.
- create the issue in English
