### ISSUE TITLE
BIM Workbench - wrong geometry from IFC4

### ISSUE THREAD

**Issue by nickger** [FreeCAD/FreeCAD#18319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Imported geometry from IFC4 file is wrong: surfaces of revolution are not bounded correctly by the edges. Geometry originally is created in OpenCascade end exported via IfcOpenShell to IFC. Please, check the algorythm of creating faces for this case. The IFC file is attached.
[Project31_db.txt](https://github.com/user-attachments/files/18028105/Project31_db.txt)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by semhustej** [comment]
I tried changing the .txt file extension to .ifc and opening the file in multiple viewers.

- FreeCAD shows geometry
- Open IFC viewer shows some geometry
- BonsaiBIM shows some geometry
- BIMvision shows no geometry
- Autodesk viewer shows no geometry

This seems like a quite difficult file to interpret. 

FreeCAD:

![freecad-geometry](https://github.com/user-attachments/assets/efab39d8-aaf4-4133-bd2e-c0867e1fb8b8)


BonsaiBIM
![bonsaibim](https://github.com/user-attachments/assets/db1f229e-4e2b-4bae-83a7-1b5aa2c539fd)


OpenIFC viewer
![IFC-open-viewer](https://github.com/user-attachments/assets/253f1119-1147-4d15-b470-83d8b5af9c40)


BIMVision
![BIM-vision](https://github.com/user-attachments/assets/a5ed1be2-912b-4738-9c04-de2489673bbc)


Autodesk
![autodesk](https://github.com/user-attachments/assets/a6d4023b-57fc-4d04-a266-d7043e21a1be)



```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

```

**Comment by nickger** [comment]
I am very sory, looks like the reference image from OpenCascade was not attached. 
![Geom](https://github.com/user-attachments/assets/4fa99de2-470c-4205-a7d7-0a387d3250a1)
This is how it looks. If I convert all surfaces to NURBS and export to IFC, it works and looks correct. But as you see yourself, different viewers show different geometry.

**Comment by maxwxyz** [comment]
Does other files have issues as well or is it just this file?

**Comment by yorikvanhavre** [comment]
This object is an `#436=IFCADVANCEDBREP(#435);` which is a NURBS object. Although this is indeed supported by IfcOpenShell, it apparently still has hiccups (their own viewer at https://viewer.ifcopenshell.org/ , although it does a better job than the others, also shows some defects). Note that almost no commercial BIM app out there is able to support NURBS objects... Certainly not the big, expensive commercial ones ;)

Since it is ifcopenshell that builds the shape in FreeCAD, this is basically an IfcOpenShell bug. I would suggest opening an issue at https://github.com/IfcOpenShell/IfcOpenShell

**Comment by maxwxyz** [comment]
If I understand correctly, fixing this in IfcOpenShell will make it work in FreeCAD in the future?
Closing this then.

**Comment by yorikvanhavre** [comment]
Yes, there is anyway nothing we can do on FreeCAD's side, apart from helping transferring the bug report to IfcOpenShell...

**Comment by luzpaz** [comment]
Heads up @aothms (https://github.com/FreeCAD/FreeCAD/issues/18319#issuecomment-2523289427)

**Comment by aothms** [comment]
These kind of 'snail/donut artefacts' as we used to call them were quite specific to revolutions and OCCT 7.8. We have a workaround though, you could try upgrading. https://github.com/IfcOpenShell/IfcOpenShell/issues/5064

**Comment by aothms** [comment]
@nickger True, I think pcurves are still ignored in the source data, also because there is approximately 0 public models available that embed pcurves into the exchange. This also applies to things like topological vertex loops. In that sense shapefix posthoc works nicely, because it works regardless of whether parametric data is present or not.

One person within Bentley (now no longer working there) at some point tried to work towards some sample models for adv brep ifc. If you have models with pcurves, maybe publish them there and see if there is some response form the vendors. https://github.com/buildingsmart-community/Community-Sample-Test-Files/tree/main/IFC%204.0.2.1%20(IFC%204)/NURBS

**Comment by nickger** [comment]
For sure they are ignored as they duplicate the information: as soon as one has 3d curve and surfaces, he needs to calculate the projections. OpenCascade does it implicitely only for curves on planes, the rest must be calculated by using ShapeFix_Edge::FixAddPCurve. Important is that the initial data store the orientation of edges in bounding loops as this function creates pcurves always in direction of current edge orientation. Nevertheless, this alone is not enough - after calculating pcurves and adding edges to wires, one need to run ShapeFix_Wire::Perform to be entirely sure that UV coordinates are all correct (especially on periodic surfaces) so the face will be constructed correctly by BRepBuilderAPI_MakeFace.
This is what I meant when I said that math comes first: only when you do everithing right in parameteric spaces you can expect correct topology construction. The tool ShapeFix_Face is too generic, from my experience it works 50/50 and for some reason it does make difference: whether you try to correct already created topological structure or you correct its parts first and construct it from the corrected parts.
