### ISSUE TITLE
problems importing 3D DXF

### ISSUE THREAD

**Issue by juanpc2018** [FreeCAD/FreeCAD#18454]
most 2D DXF import Ok.

.py module complains.

example 2D & 3D DXF test files:
https://jblpro.com/en/support_downloads/download_types/caddrawing

**Comment by yorikvanhavre** [comment]
The files there that are composed of explicit entities (lines, arcs,...) open fine:
![image](https://github.com/user-attachments/assets/85970bec-0346-4816-a254-8797bfee05a7)

Those that don't import are using ACIS solids, which is a "blob" in a proprietary format inside the otherwise open DXF file. FreeCAD cannot read ACIS blobs, as stated in the documentation.

Autodesk ACIS format is a proprietary, undocumented format, it's different from the original ACIS format (which is somewhat documented), and we have no way to support it with the means of a FOSS project like FreeCAD (it would swallow all our resources to do heavy and imperfect reverse-engineering). Unfortunately, working with proprietary formats is always a PITA...

So at the moment we have no way to solve this, your best path would be to use a proprietary app able to open those files and convert them to an open format like STEP.

I'll close this as there is no action for us to undertake, but please reopen if I misunderstood anything

**Comment by juanpc2018** [comment]
IF DXF does Not work,
what works?

converting DXF to STL ?
importing STL ?
