### ISSUE TITLE
Core: Ability to Ctrl+Drag shortcut in the tree to copy

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#18461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

A frequently found shortcut is Ctrl+Drag&Drop to copy an element, this shortcut doesn't exist yet for the object tree. Should be great to add.

### Full version info

```shell
any
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Copy only the original selection or all related dependencies?
@PaddleStroke is this feasible to integrate in the tree view dragging?

**Comment by PaddleStroke** [comment]
I seem to recall that we already have this. RT introduced such behaviors. But it was kind of a mess and generating issues, especially because the special mode were happening without modifiers depending on the context. This was removed. But the special modes on modifier should still work.

I seem to recall that the modifiers where shift and alt.
However I have tested and did not find any combinaison that copy the object. I think the only copying was happening when the object could not be dragged from the parent, then it was making a copy automatically (without modifiers) which was generating issues.

Longstory short, yes it can probably be done. However because copy paste is kind of a mess I don't know how it going to be.
