### ISSUE TITLE
Multiselection mode

### ISSUE THREAD

**Issue by yan695432** [FreeCAD/FreeCAD#18540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

How to save Multiselection mode in a custom workspace without modifying the source code

### Full version info

```shell
1.0.0RC2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Please check out how to [report issues](https://github.com/FreeCAD/FreeCAD?tab=readme-ov-file#reporting-issues) which could help us diagnose and fix it.

- Test if the issue is still present in the dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
- add full [About](https://wiki.freecad.org/About) info to the issue (`Help > About FreeCAD > Copy to clipboard`).
- add steps to reproduce the issue

If it is a help request, try reaching out on the Forums.
I'll reopen when there is more info in actionable form.
