### ISSUE TITLE
[Problem] FreeCAD lacks a "Quick Start" Dialog

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5772]
Problem 
=======

When first launching FreeCAD users lack a means of configuring simple preferences that will allow them to start work in FreeCAD quickly and without much effort required. This applies both when the application is first launched on a system and during subsequent launches.

Explanation: 
==========

Users have different needs that set defaults cannot reliably predict. These are items such as language, units, and classic vs light vs dark themes. High-performance computers can tolerate higher quality visual configurations vs older machines or single-board computers such as a Raspberry Pi, so a simple toggle to enable high vs low graphics configuration instead of expecting a user to find and understand the nuance of the many settings available to the power user. Such simplifications can set broadly understood and highly individual preferences.

### Original issue details

Issue imported from https://tracker.freecad.org/view.php?id=3393

* **Reporter:** @luzpaz
* **Date submitted:** 3/26/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** #lowhangingfruit

### Original report text

Inspired by this thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=27623&start=10#p223411
Discussion thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=27691

!(https://forum.freecadweb.org/download/file.php?id=55427)

[quote=NormandC]But wouldn't the best be to open a configuration wizard when launching FreeCAD for the first time? Something like what LibreCAD has, but extended. It could give you the possibility to set your units, define your mouse model (explanation window required, similar to Navigation Indicator), even TechDraw template size.

Going further, we could introduce "custom profiles" in the wizard that would automatically filter the workbench list to different selections.

    * Architecture profile would filter the wb selector to only display Arch, Draft, Sketcher, Spreadsheet, TechDraw and possibly a few others (Mesh Design? Part? Raytracing?)
    * Mechanical Design profile would filter the wb selector to only display Sketcher, PartDesign, Spreadsheet, TechDraw, Mesh Design, FEM and possibly Raytracing and Draft
    * General modeling profile would display Draft, Sketcher, Part...
    * Complete profile would display all installed workbenches.
[/quote]

# Additional information

Here is the librecad code:
ui: https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/ui/forms/qg_dlginitial.ui
cpp: https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/ui/forms/qg_dlginitial.cpp
h: https://github.com/LibreCAD/LibreCAD/blob/master/librecad/src/ui/forms/qg_dlginitial.h

# Other bug information

* **Priority:** low
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @luzpaz 2018-07-29 11:54
Wikilab team has started to tackle this issue in:
https://forum.freecadweb.org/viewtopic.php?f=10&t=29610

---

### Comment by silas 2019-01-21 18:21
Hi. Just communicating we Wikilab (https://lab.wiki.br) are still working on that.  We couldn't finish it before 0.18 and we are in school holiday period, we are in very slow pace, but but we are still on this issue.

If want to see [slow] progress, check the branch: https://github.com/wikilab-abc/FreeCAD/tree/config-wizard

---

### Comment by @luzpaz 2020-10-14 20:41
silas looks like development stalled. What is the status of the wizard ?

---

### Comment by silas 2020-12-12 19:37
Hi! Sorry for taking so long to send a reply. It happened that the group had vanished, so we halted the development. Consider it will not be done by our group in the short term. Sorry for that and thank you for the opportunity.

**Comment by MisterMakerNL** [comment]
I picked it up a bit but still the hard work of making the coding has to be done:
![afbeelding](https://user-images.githubusercontent.com/29804962/200181000-51f7ca39-3c3c-493a-82f5-677e0e2dda2a.png)
Screenshot is from QT designer.

**Comment by sliptonic** [comment]
If the user intends to do CNC/CAM they need to select a unit schema that supports velocity as units/min and not units/second.  For example "metric, small parts and CNC".

Perhaps selecting intended use could trigger subsequent wb specific configuration or 'tips'

**Comment by MisterMakerNL** [comment]
@sliptonic Good point I also was thinking about it, same is for Techdraw settings like sheet formats.
Although my main worries are currently just getting this too work. Adding stuff later would probably not be too hard. 
So start simple, get it too work and test it in 0.21 while it isn't released. Then adjust or scrap.

**Comment by silopolis** [comment]
Le dim. 6 nov. 2022 à 20:43, sliptonic ***@***.***> a écrit :

> If the user intends to do CNC/CAM they need to select a unit schema that
> supports velocity as units/min and not units/second. For example "metric,
> small parts and CNC".
>

👍

Perhaps selecting intended use could trigger subsequent wb specific
> configuration or 'tips'
>

Or maybe move the units choice bellow intended use as it is indeed very
much linked to it?
The most probable option could then be selected depending on language and
use choices.

**Comment by onekk** [comment]
Why "intended use", im my opinion this could lead to some misunderstanding, as it may seems that the configuration is settings things for a specific use.

Probably something that will explain clearly that this will not prevent to use FreeCAD for other use will be welcomed.

And probably less granular things in first screen, I could think of "three big areas" where FC could be used:

- Mechanical design (and some sub choices in subsequent screen about units imperial or metric, probably with some distinction between "precision mechanics" and "steel work" to be very harsh in description)
- Architecture (maybe this will even set the preferred WB at start to be "Arch WB")
- Technical drawing that maybe will guide you to some settings related to "TechDraw"

More granularity in subsequent screens, some examples: 

- "3d printing"  and "CNC" could be comprised in "mechanical design" and managed by some subsequent question, as probably most settings are somewhat "in commont" between the two use cases, most 3d printers firmware did not support from what I know "imperial units", and that mm is the preferred unit instead of km or metres, for both things, but usually you don't generate GCode for 3d printers,but STL files instead, as slicing is better handled by a dedicated software. IMHO velocity, will be be better related to "postprocessor settings", and probably inserted in some question when creating first "Path Job", as it seems more related to "machine controller settings" more than to be related to the whole FreeCAD itself.
- "Rendering and animation" I don't see what could be different settings.

As FreeCAD is complicated, why overcomplicate first steps, usually when dealing with complications, "elephant vs ant rule " is better than a bunch of choices in the first place (NdA: "elephant vs ant rule", is simple a joke, how does an ant eat an elephant? In very small pieces :-D)


Regards

Carlo D.

**Comment by luzpaz** [comment]
Note: this is also being discussed: 
* on the forum: https://forum.freecadweb.org/viewtopic.php?f=34&t=71277
* https://github.com/howie-j/FreeCAD-Wizard  

@MisterMakerNL where are you working on your template?

**Comment by MisterMakerNL** [comment]
@luzpaz I also forked it. https://github.com/MisterMakerNL/FreeCAD-Wizard

**Comment by MisterMakerNL** [comment]
I did some work on this this evening, but it is more learning QT then doing a lot of progress....
Found this commit from another project, which shows pretty much how it is done. Although the screenshots show a massive ui. And I cannot find the ui.
https://github.com/Nazardo/QEbu/commit/88c602ebd8751b06784e59e17c19c859c1231b02
I made it this far:
![afbeelding](https://user-images.githubusercontent.com/29804962/201544502-7cb6a3d2-bbb8-498a-966c-9367c53418b6.png)
But now it is all coded.....

**Comment by luzpaz** [comment]
Nice job @MisterMakerNL ! Really appreciate your work on this!

BTW, some time ago @studiopetrikas shared an idea for a mockup that he made (although it's slightly off topic, i was more referring to the stylistic approach)
![Freecad mockup](https://user-images.githubusercontent.com/4140247/201550525-cd7045fd-71b2-4590-9783-d5ccf17c5d38.jpg)

**Comment by MisterMakerNL** [comment]
@luzpaz Looks good! But lets try the wizard first :)
Got a little further still have not figured how to add a groupbox to the code, but I will one day!
![afbeelding](https://user-images.githubusercontent.com/29804962/201758922-b9aaa727-5499-428a-8e41-e03e2780e97d.png)

**Comment by obelisk79** [comment]
If possible, I think this issue would be best revised as such:
Title: [Problem] FreeCAD lacks a "Quick Start" Dialog

Problem: When first launching FreeCAD users lack a means of configuring simple preferences that will allow them to start work in FreeCAD quickly and without much effort required. This applies both when the application is first launched on a system and during subsequent launches.

Explanation: Users have different needs that set defaults cannot reliably predict. These are items such as language, units, classic vs light vs dark themes. High performance computers can tolerate higher quality visual configurations vs older machines or single-board computers such as a Raspberry Pi, so a simple toggle to enable high vs low graphics configuration instead of expecting a user to find and understand the nuance of the many settings available to the power user. Such simplifications can set broadly understood and but highly individual preferences.

**Comment by sliptonic** [comment]
I've updated the title and first comment.   Thanks for improving this issue.

I retained the original information for historical purposes.

**Comment by FEA-eng** [comment]
@maxwxyz Thanks to #13650, there is a first start widget now (just very simple and should be expanded in the future) so maybe the issue could be closed in favor of new ones with suggested improvements for this widget.

**Comment by katepavlu** [comment]
@maxwxyz 
- an initial vesrion of this is already implemented
- the discussion seems to have switched to #11735 for a while
Is there any reason this should remain open?

**Comment by maxwxyz** [comment]
Yes, further discussion in https://github.com/FreeCAD/FreeCAD/issues/11735
