### ISSUE TITLE
[Feature Request] TechDraw: Allow manual entry of the main direction (the front) for a ProjectionGroup

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5821]
Issue imported from https://tracker.freecad.org/view.php?id=3646

* **Reporter:** vocx
* **Date submitted:** 10/21/2018
* **FreeCAD version:** 0.18
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

If a body's face is selected, and the user creates a ProjectionGroup, the projection direction is normal to that face. If no face is selected, the projection uses the 3D camera angle.

However, Sketches don't have a face so if the user tries to create a projection normal to that Sketch, he has to rely on adjusting the camera first before calling the ProjectionGroup tool.

An option to manually define the main direction (the front) of the ProjectionGroup could be added, so that selecting a face, or changing the 3D camera is not necessary.

The feature was first requested in the old TechDraw repository https://github.com/WandererFan/FreeCAD-TechDraw/issues/65 by @ceremcem

> [Supposedly introduced with](https://github.com/realthunder/FreeCAD_assembly3/issues/100#issuecomment-421721880) https://github.com/FreeCAD/FreeCAD/commit/aa8feb79d0ab6766f736161f9fdd722ac80817f9, TechDraw generates 3D projection of a sketch by using current camera angle but we can't select a face of a sketch since it has no face.
> ### Proposal
>
> A button (or a context option on the input) to reset the projection angle to `[1.00 0.00 0.00]` would suffice in the task window:
> ![image](https://user-images.githubusercontent.com/4140247/205491165-22b90faa-70d2-4933-8683-4a5be826238b.png)

Now it's in the forum https://forum.freecadweb.org/viewtopic.php?f=35&t=31041

# Additional information

OS: Ubuntu 18.04.1 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14995 (Git)
Build type: Release
Branch: master
Hash: 7b866816785ac1ca9787b63d4bff12873bb3a593
Python version: 2.7.15rc1
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 3/7/2021

# Discussion from Mantis ticket

### Comment by @donovaly 2019-01-28 16:16
This issue also popped up in this discussion:
https://forum.freecadweb.org/viewtopic.php?f=35&t=33776&p=282993#p282993

**Comment by donovaly** [comment]
@WandererFan , maybe you have time to have a look?

**Comment by luzpaz** [comment]
@WandererFan can you weigh-in on this ticket when you get a chance ? If possible provide any tips for devs that may be interested in helping add this feature?

**Comment by WandererFan** [comment]
There is a read only field (lePrimary) in the ui that displays the Front view projection direction, as determined from the selected face or camera angle.  

This could be changed to vector entry fields with appropriate slots to update Front's Direction property, and then update the directions of the rest of the views in the group.

In fact, you achieve the same end (once the group is created) by editing the Front view's Direction in the PropertyEditor.  Might need a recompute or redraw, but that is normal.

In the case mentioned in the comments above, why would anybody want a projection group of a Sketch?  A sketch is a 2d object and looking at it from the side doesn't make a lot of sense.

To me, this is a real niche request, which is why it has hung around so long.

**Comment by luzpaz** [comment]
Thanks WandererFan.

@ceremcem can you respond to the validity of this edge-case ?

**Comment by ceremcem** [comment]
ASAP

**Comment by WandererFan** [comment]
If I reread this FR, it seems to be mostly about having to align the 3d camera to make a 2d view of a sketch.  

There is code in Import that finds the sketch normal.  We could use that to set the direction of a View (or Projection Group), if the only Source object is a sketch.

**Comment by maxwxyz** [comment]
Remarks from the FreeCAD Day 2024 Complaint Session:
If you insert a view, it tends to bring in based on how the model is currently rotated in a different region not currently looking at. Rather than just giving you the front front.
The orientation of that view depends on how your camera is currently positioned rather than on the orientation of default view.
