### ISSUE TITLE
Negative numbers with multiple units interpeted as expressions

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5909]
Issue imported from https://tracker.freecad.org/view.php?id=3925

* **Reporter:** metatheorem
* **Date submitted:** 4/4/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** units

# Original report text

When typing in a negative measurement, such as in the Draft Move tool, combinations of units are interpreted as an addition expression.  For example, the expression "-1m 10mm" is evaluated to "-990.0 mm" instead of "-1010.0 mm" as it should be.  This appears to happen regardless of the units used.

Forum disussion here: [Negative numbers in feet/inches interpreted wrong](https://forum.freecadweb.org/viewtopic.php?f=3&t=35401&sid=cf46dba2369d767772ccde09b3448bb8)

# Additional information

This can happen either when a text entry field loses focus or when a tool is applied.

Workarounds:
1. If possible, key in a single type of unit.
2. If not possible, such as when working with feet and inches, perform two operations that add up to the desired measurement.  This may not work for all operations.

OS: Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.Unknown
Build type: Unknown
Python version: 2.7.15
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 6.9.1.oce-0.18
Locale: English/UnitedStates (en_US)

# Steps to reproduce

1. In the Draft workspace, create a two-point rectangle.
2. In any of the point value fields (x, y, or z), type in an expression such as "-1m 10mm".
3. Move keyboard focus away from the field, and the entry changes to "-990.0 mm".

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 1/23/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2019-04-24 11:19
In the future, please follow our guidelines (mentioned in the yellow banner at the top of the page)

How did you build FreeCAD?
Can you please try with a Qt5/Py3/OCC7.3 build?
https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.1
or even better try the 0.19_pre 
https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre

---

### Comment by Geoplace 2019-04-27 03:46
Hi

I've teste the version 18.1

But there is the same behavior.
1.-Draw a line.
2- Change its X end point typing -1m 10mm the result was -990mm instead of the -1010mm

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16110 (Git)
Build type: Release
Branch: (HEAD detached at upstream/releases/FreeCAD-0-18)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0

---

### Comment by Kunda1 2019-06-13 04:49
Another relevant forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=35209

**Comment by eshattow** [comment]
This bug hits FreeCAD 0.20 and makes working with FreeCAD unreliable.

Position x: 28'9+3/4"
Position y: -13' 7+1/4"
Position z: 0

When focus/defocus each of those fields the result is follows.

Position x: 28'9+3/4"
Position y: -12' 4+3/4"
Position z: 0

All subsequent focus or defocus results in position y being evaluated and self-modified because it is evaluated as this bug issue report describes.
-11' 7+1/4"
-10' 4+3/4"
-9' 7+1/4"
-8' 4+3/4"
and so on.

This should not be possible from UX perspective because user entry of formulas "f(x)" is a different action than typing in a literal value. Yet we have this impossible expression placed in the literal value entry and evaluated so self-modifying every focus or defocus.

Attempting to purposefully move this literal into the Formula editor 
Position y f(x): -13' 4+3/4"
there is an error "Failed to parse expression". It can only be entered as:
Position y f(x): -(12'+4"+3"/4)
however this is not actually valid when accepting and leaving focus, the error is:
`16:19:32  Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'SyntaxError'>: ('unterminated string literal (detected at line 1)', ('<string>', 1, 105, 'App.getDocument(\'documentname\').Sketch060.setExpression(\'.Placement.Base.y\', u\'-(12\' + 4" + 3" / 4)\')', 1, 105))
`

What is successful:
Position y f(x): -(12*12"+4"+3"/4)

There are a few problems in FreeCAD handling of unit literals here.

1. Negative sign is represented naked without parenthesis when editing unit literal and for display
2. Unclear handling of complex units for editing
3. 

Position y: -13' 7+1/4"
should instead on editing and display be
Position y: -(13' 7+1/4")
however the 7 in this example is ambiguous. It should be more explicit as
Position y: -(13' 7"+1/4")
yet this is still not allowed since the unit literal 13'7" is variously accepted or not accepted throughout FreeCAD (Spreadsheet, formula entry, literal entry, BIM field entry) and results in inconsistent behavior at input. So we should insist on consistent behavior as
Position y: -(13'+7"+1/4")
and that is unfortunately not valid though I would say this is the real bug it should be allowed to enter mixed units into the formula editor f(x) when each component of unit entry is fully qualified with a unit identifier.

The user workaround is to avoid working with negative units, fractional units, and mixed foot and inches within the same drawing
-or-
when you have a part jumping around on you everytime focus/defocus the field due to this bug be aware
Position y: -13' 7+1/4"
to change for example into
Position y f(x): -(13*12"+7"+1"/4)

**Comment by adrianinsaval** [comment]
`1m 10 mm` is not supported syntax AFAIK, write `1.010 m` or `1m + 10mm` instead. Mathematical operations are supported in the input boxes so certain syntax rules are required. The parser was changed recently also so behavior for some of these situations might have changed in latest dev versions, however unsupported syntax will still fail.

**Comment by eshattow** [comment]
> `1m 10 mm` is not supported syntax AFAIK, write `1.010 m` or `1m + 10mm` instead. Mathematical operations are supported in the input boxes so certain syntax rules are required. The parser was changed recently also so behavior for some of these situations might have changed in latest dev versions, however unsupported syntax will still fail.

Fractional data entry UX should be consistent across mixed-units. It is clear what the intent is of `1m 10+3/4in` or `3.2yd 20/4mm` even if these are silly use cases. These are user input & display data not simple mathematical operations. What is not easy to parse we should make easier to parse: bracketing for mixed-value statements?

`[3.2yd 10ft 3/4in 6m 4in]` => re-ordered to relative size of each unit `[3.2yd 6m 10ft 4+3/4in]`

`[3.2yd 6m 10ft 4+3/4in] * 4` => distribute the multiply `[12.8yd 24m 40ft 19in]`

optional type conversion heuristics between compatible fractional and decimal units
`[12.8yd 24m 40ft 19in]` => at 1/8th inch resolution `[13yd 24m 34ft 4.1 + 1/2in]`

unit-less zero
`[1m 10mm]` => positive method A
`0+[1m 10mm]` => positive method A
`0-[1m 10mm]` => negative method A

unary positive or negative within the brackets leading the value.
`[+1m 10mm]` => positive method B
`[-1m 10mm]` => negative method B

methods A and B reserved for whatever makes the most sense, for example type conversion heuristics on or off. The user should be able to express the value as "I entered this. Leave it alone, it's fine like it is." or as "Can you please re-shuffle this and make it better for me? Thanks." This is where "zero" needs to be unit-less, so you can do something like
`0+[+1m 10mm]` => ?
`0+[-1m 10mm]` => ?
`0-[+1m 10mm]` => ?
`0-[-1m 10mm]` => ?

`[1m 10+3/4in] / 3` => distribute the division `[1/3m 10/3+3/12in]`

Looks weird? Users do weird things and that is okay. They can fix their mistakes but we should not introduce new mistakes by assuming absolutely everything is a mathematical expression.

I don't know if we're using brackets already for anything, but something like this would be easy to convey to the user as "Tip: use brackets for fractional and mixed-unit values".

**Comment by adrianinsaval** [comment]
I really don't see the appeal of supporting these niche and weird syntax, about brackets I'm not 100% sure but I think they are used for vectors

**Comment by eshattow** [comment]
> I really don't see the appeal of supporting these niche and weird syntax, about brackets I'm not 100% sure but I think they are used for vectors

What would you say about having to write `-1'4-3/4"` as `(0"-(1*12"+4"+3"/4))` ?

I can't put `(0"-(1*12"+4"+3"/4))` on a technical drawing, the local government will not accept it for construction plans.

FreeCAD should have a workflow for data entry that does not make it worse than what the user input is.
