### ISSUE TITLE
[regression] DXF export option "project exported objects along current view direction" no longer working

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6001]
Issue imported from https://tracker.freecad.org/view.php?id=4180

* **Reporter:** @donovaly 
* **Date submitted:** 10/29/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** DXF, export

# Original report text

Sketches that are not in the XY-plane are no longer correctly exported to DXF, despite the DXF export option "project exported objects along current view direction" is used.

It only works if you use additionally the option "use legacy python exporter". However, it must also work without it.

In FC 0.18 there is no legacy exporter and everything works fine there -> regression.

# Additional information

Forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=40424

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18637 (Git)
Build type: Release
Branch: master
Hash: e243c6e943dc78e7e8093c5c38a879e46b37d0c1
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)
```

# Other bug information

* **Priority:** high
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by PAS-DRAFTER** [comment]
[https://forum.freecad.org/viewtopic.php?t=77005](url)

I just noticed that this bug report was created last year after running into the problem yesterday using

`OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.31917 (Git)
Build type: Release
Branch: master
Hash: 4639283b459f9ff9093e289908cc003db8745b82
Python 3.10.9, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.12.5
  * CurvedShapes 1.0.4
  * Curves 0.6.5
  * fasteners 0.4.53
  * sheetmetal 0.2.60
`
I expect my problem is caused by the same issue.

**Comment by luzpaz** [comment]
@yorikvanhavre since there has been some work on DXF exporter, is this on anyones radar ?

**Comment by yorikvanhavre** [comment]
I had forgotten about this one... Will check!

**Comment by yorikvanhavre** [comment]
Ok, the option above still works, but ones has to use the legacy exporter. The above PR makes this clearer by indicating which option applies to legacy exporter/importer only.
