### ISSUE TITLE
[Problem] Part: Problem in using the sweep function

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6211]
Issue imported from https://tracker.freecad.org/view.php?id=4651

* **Reporter:** Daniele75
* **Date submitted:** 5/1/2021
* **FreeCAD version:** 0.19

# Original report text

I found a bug when making springs that occurs in version 19, while up to 18 it worked smoothly.

![image](https://github.com/FreeCAD/FreeCAD/assets/4140247/2ec72516-eb76-42b8-9764-6857a858bfee)

ref: https://ibb.co/1dN5CMq

# Steps to reproduce

1° new file
2° goto "Part" ambient
3° creates parametric geometric primitives
4° Propeller
5° set dimension: pitch 0,75 ; height 3mm ; radius 1,3mm
6° Create Propeller ( Ok ) 
7° goto "Sketcher" ambient
8° Create new Sketcher
9° Select XZ floor
10° Create circle
11° Set constraints...  radius 0,2mm ; height from y axis 0mm ; distance from x axis 1,3mm ( same than radius of propeller )
12° close
13° goto "Part" ambient
14° select Sweep utilities
15° Select Sketch from list available profiles
16° bring to selected profiles
17° select all the propeller in the draw ( black to green color )
18° check create solid  + frenet
19° OK

the sweep obtained is corrupted.

# Other bug information

* **Priority:** high
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 Home 20H2**
* **Updated:** 5/13/2021

**Comment by plaes** [comment]
I ran into this issue when using 0.21.2 / git 33771 / b9bfa5c5507506e4515816414cd27f4851d00489 (Flatpak image).

It seems to be caused by certain multipliers for helix pitch (for example 3mm and 6mm):

Steps to reproduce:
1. Create helix: Pitch 6mm (or 3mm), Height 30mm, Radius: 8mm
2. Sketch a sweep pattern (circle on Object's XY plane, select helix as external geometry)
3. Sweep in Part workbench (Translation increment 2mm, rotation: 10 degrees)
4. Observe broken spring in 3D:
![pitch-6mm](https://github.com/FreeCAD/FreeCAD/assets/91895/d66a5ee8-74b0-433f-9e2c-542f4fc8de57)
![pitch-3mm](https://github.com/FreeCAD/FreeCAD/assets/91895/10c2858a-94bb-44c5-b32f-d253fd3f4726)

If I change Helix pitch to any other value (tried a lot different values from 2 .. 9mm), result looks ok:
![image](https://github.com/FreeCAD/FreeCAD/assets/91895/6f77624f-6a7e-4ce5-9b50-234ba408dadc)

Some other broken values: 3.01 and 6.02 (but not 6.01).

Part here compressed as ZIP:
[spring.zip](https://github.com/FreeCAD/FreeCAD/files/13466761/spring.zip)

**Comment by luzpaz** [comment]
@plaes can you also test on the 0.22 development build ?

**Comment by plaes** [comment]
> @plaes can you also test on the 0.22 development build ?

Yes, still present with latest one from https://github.com/FreeCAD/FreeCAD-Bundle:
>  FreeCAD 0.22.0, Libs: 0.22.0devR35209 (Git)

**Comment by luzpaz** [comment]
@bgbsww want to take a swipe at this ?

**Comment by luzpaz** [comment]
Thanks bgbsww for sleuthing this as far as you could. @FlachyJoe can you weigh-in ?

**Comment by bgbsww** [comment]
~~Does that translation increment / rotation dialog actually do anything?  Or does it just come along for the ride as part of the ... --> ViewProviderExtrusion --> ViewProviderPart --> ViewProviderPartExt --> ViewProviderGeometryObject --> ViewProviderDragger inheritance path?~~  Oh, I see, that opens the transform widget, and those control what the transform widget does, but never affects the actual object directly.  Learned something today :)

**Comment by bgbsww** [comment]
Yeah, I can't let go of this bone.  So, I think we're at this: 
https://github.com/FreeCAD/FreeCAD/blob/94ca51b7799b2ac60a2a56d7e6e753bb97a73671/src/Mod/Part/App/PartFeatures.cpp#L539-L541  and there are a bunch of setMode options: https://dev.opencascade.org/doc/refman/html/class_b_rep_offset_a_p_i___make_pipe_shell.html#a0e026a22a00587b3d36faffbcb68a2c9 
The simplest option would just be to force isFrenet, but I'm not sure about the cases where this would cause a problem.

I still don't really understand this, just adding data points.

**Comment by bgbsww** [comment]
OK!  I'm not crazy.  @luzpaz assign me please, and we'll get this knocked out.
