### ISSUE TITLE
[Bug] sheet metal V 0.2.53

### ISSUE THREAD

**Issue by sorag** [FreeCAD/FreeCAD#7272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

Link

### Version

0.20 (Release)

### Full version info

```shell
Versione 0.20
N v. 29177
Data 2022/06/13
Sistema operativo Windows versione 2009 64bit
```

### Subproject(s) affected?

PartDesign

### Issue description

La versione aggiornata di sheet metal non funziona correttamente da errori 

### Anything else?

![16590924740204825889698698098366](https://user-images.githubusercontent.com/55976663/181745881-7c630a25-dbfe-4b8e-bc66-069abec72dff.jpg)
![16590925287306850691580760973386](https://user-images.githubusercontent.com/55976663/181745966-e343ba9f-6a74-40eb-93be-741b391877b9.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Note:   
* Sheetmetal workbench is an external workbench (https://github.com/shaise/FreeCAD_SheetMetal) that has it's own issue queue. 
* Link branch has it's own issue queue as well (https://github.com/realthunder/FreeCAD). 
* Please follow guidelines by posting your issue to the forum first. 
* Also always paste your full [About](https://wiki.freecad.org/About) info when you do. 
* Another tip is to use screenshot software instead of your phone to take screenshots (there's no need to upload extremely large images if not necessary)

Closing ticket.
