### ISSUE TITLE
[Problem] Tech Draw: Measure Type = True always returns 0

### ISSUE THREAD

**Issue by reald** [FreeCAD/FreeCAD#8203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.1 LTS (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31622 (Git)
Build type: Unknown
Branch: master
Hash: 199ef42f625aafdda03be4d5cd8bb311fa98abdc
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: German/Germany (de_DE)
[/code]
```

### Subproject(s) affected?

Techdraw

### Problem description

Steps to reproduce:
1. Add some distance measurements to a tech draw. 

![Screenshot_20230117_115200](https://user-images.githubusercontent.com/1385404/212881086-b5ed61db-c600-44ce-89fb-67703fc9d851.png)

2. Change "measure type" from "Projected" to "True"

![Screenshot_20230117_115113](https://user-images.githubusercontent.com/1385404/212881067-85d7edaf-cdef-47f8-9672-b5bc28901653.png)

Result: All changed measurements will have 0 length instead of the true length.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
Does the dimension have 3d references?  If not, it can not calculate the True value

**Comment by reald** [comment]
Thanks for the tip! 3D reference has to be added as described here:

https://wiki.freecadweb.org/TechDraw_LinkDimension

**Comment by caco3** [comment]
I have the exactly same issue and can't figure out how to fix this..

![grafik](https://user-images.githubusercontent.com/1783586/230800284-d705b37d-ed43-4e89-892a-62c9a1dbd759.png)

I am using the Linux version (snap, 0.20.2, 64bit)

Example file:
[techdraw.zip](https://github.com/FreeCAD/FreeCAD/files/11186473/techdraw.zip)

**Comment by WandererFan** [comment]
How did you get the same dimension object in 2 different views?  That isn't supposed to happen.

True dimensions are only available for dimensions with a reference to the 3d model.  Otherwise 
only the projected dimension is available.

There should have been a message a some point: 
11:31:34  Dimension001 - True dimension has no 3D References

In v0.20 you'll have to use LInkDimension command as mentioned above.  In v0.21 you can create 3d references by point and click.

**Comment by caco3** [comment]
Thanks for asking back.

I tried to follow the instructions at https://wiki.freecad.org/TechDraw_LinkDimension but obviously I understrood it wrong.
I now finally found a video which shows how to do it correctly: https://www.youtube.com/watch?v=vOUZB0mMKKA

I think my mistake was on in step 2: I selected the edge in the **TechDraw** tab instead of the **Parts** tab.
