### ISSUE TITLE
[Problem] Opening an image from the file menu is confusing and not useful

### ISSUE THREAD

**Issue by julia-m-stephenson** [FreeCAD/FreeCAD#8556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.5
  * fasteners 0.4.27
[/code]
```

### Subproject(s) affected?

None

### Issue description

When opening a PNG file the view seems to be constrained to a letter box. 

![image](https://user-images.githubusercontent.com/52968628/220046269-d2c4f180-2e01-4b42-862d-fb6f7320fc71.png)

If you zoom in and out using the scroll wheel it displays tiny.

![image](https://user-images.githubusercontent.com/52968628/220046639-d5ed7a6e-743e-4c95-9a05-82d07ad13a6c.png)

As a workaround I opened the file in inkscape and saved as SVG. This file was opened as a drawing and displayed correctly.

![image](https://user-images.githubusercontent.com/52968628/220047024-bff7a141-62a6-4d67-9cbe-fec6d3579c74.png)

Here is the PNG.
![DeckEyePlateInstructions](https://user-images.githubusercontent.com/52968628/220047133-67739b5a-7c90-4dea-a5b0-f46eef91c307.png)

Here is the SVG.
![DeckEyePlateInstructions](https://user-images.githubusercontent.com/52968628/220047135-417c5a11-f409-4df6-8f42-09fd836c3c1a.svg)

Thanks. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment]
How are you "opening" the file?  What command? What workbench?

**Comment by julia-m-stephenson** [comment]
> How are you "opening" the file? What command? What workbench?

File->Open

**Comment by WandererFan** [comment]
I didn't know png was a valid import type.  I don't think this works in v0.21.

You could add the image to a TechDraw Page with [TechDraw_Image](https://wiki.freecad.org/TechDraw_Image).

**Comment by julia-m-stephenson** [comment]
It's in the list of supported file formats. 

https://wiki.freecad.org/Import_Export

It almost works just the zoom levels are incorrect. 

This isn't hugely important to me. I'm just raising it as an issue so people know about it. Maybe it's an easy fix or maybe it's something the development team want to drop .

**Comment by sliptonic** [comment]
Opening the image isn't terribly helpful since it just opens the image in a new tab and you can't really do anything with it.  To be honest, I don't know why this functionality exists.

If you want to use the image as a reference, go to the image workbench.  import the image to an imageplane.  You can orient the plane in 3D space and scale it as needed.  Then it's useful to draw over.

**Comment by sliptonic** [comment]
@julia-m-stephenson if the imageplane does what you want,  I'm going to suggest we change the title of this PR to "Opening an image from the file menu is confusing and not useful"  
Then I'm going to suggest we remove the functionality entirely.

Maybe one of the UI oriented folks like @PaddleStroke  or one of the old timers like @yorikvanhavre knows why this exists and if it should be preserved.

**Comment by PaddleStroke** [comment]
I didn't knew FC had a basic image viewer. I don't really see the point as all OS have basic image viewers.
I think basic viewer upon opening png is useless and could be removed. However it could be interesting that opening a PNG file does either of the following : 
A - trigger the import of the image to an image plane to current document.
B - Create a new document with this image in the XY plane.

By the way, the image workbench could maybe be elaborated to enable basic image editing directly in FC.

**Comment by WandererFan** [comment]
AFAICT, in v0.21 you can not open a png file using File > Open.

**Comment by sliptonic** [comment]
> AFAICT, in v0.21 you can not open a png file using File > Open.

I can.  It's still in the supported formats list.  Opening from the File menu does the same thing as this command:

![2023-02-23_07-35](https://user-images.githubusercontent.com/538057/220922466-b4513adc-9725-4ca8-8b89-9d74700064ef.png)



> A - trigger the import of the image to an image plane to current document. (but it could be argued that this is the job of 'import').

That's a good idea.  It could automatically align the plane to the current view.

T

> By the way, the image workbench could maybe be elaborated to enable basic image editing directly in FC.

Better tools for scaling and placement but let's kick other kinds of editing down the road.

**Comment by WandererFan** [comment]
My bad.  I was using a build without the ImageWB.

**Comment by sliptonic** [comment]
FYI, several of the [complaints raised at Fosdem](https://forum.freecad.org/viewtopic.php?t=75768#p658200) were about the image workbench, scaling, and display.

**Comment by PaddleStroke** [comment]
![image](https://user-images.githubusercontent.com/19984177/225855640-44889f4a-8f3c-4888-a5d4-44f2797568c1.png)
What is the image plane icon supposed to look like?

**Comment by sliptonic** [comment]
- [X] Move Image loading to core
- [ ] Implement task panel
- [ ] Remove old Image workbench
- [ ] Revise wiki documentation

**Comment by adrianinsaval** [comment]
> What is the image plane icon supposed to look like?

I think that is a generic FeaturePython icon, not specific to image planes

**Comment by sliptonic** [comment]
PR 8955 is a significant improvement.  It specifically fixes two issues from the [Fosdem complaint session](https://forum.freecad.org/viewtopic.php?t=75768#p658200)
- Image workbench: once the dimensions are set, changing them uniformly is a pain.
- Images from Image WB show the back side as black: should be transparent, or the image reversed.

The imageplane now has a dedicated task panel that can be used to adjust the scale and maintain aspect ratio.

The PR preserves the ability to open an image in a separate MDI window.  This is deemed a feature since someone may want to look at the image in one window while editing a model in another.

This issue remains open because there is additional work to do.

As of now, there are four different ways to open the image in the MDI window and two ways to open it in an imageplane.

MDI window:

1. file->import 
2. File->Open...
3. Tools->Load 
4. Image WB toolbar button image_open

Image Plane:
1. Drag an image into the 3D window.
2. Image WB toolbar button image_CreateImagePlane

The image workbench should be considered deprecated and will eventually be removed.  When it is, MDI(4) and ImagePlane(2) will go away.

In my opinion file->import should create an imageplane and load the image.
File->open should open the image in a new MDI window
Tools->Load is redundant and can be removed.

Two-point scaling needs a reworked workflow.  AFter that, it can be incorporated into the imageplane task panel and image workbench can be removed.


Did I miss anything?

**Comment by LHC-Canada** [comment]
It would be great to have support for older model files that already have images loaded into them

**Comment by adrianinsaval** [comment]
Would removing the workbench mean that previous image planes will stop working? A migration script might be a good idea then

**Comment by adrianinsaval** [comment]
should this be closed now?

**Comment by chennes** [comment]
I think so 👍
