### ISSUE TITLE
[Issue] Image workbench controls are scattered and hidden in a wb.

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#8945]
### Forums discussion

https://forum.freecad.org/viewtopic.php?p=668562#p668562

### Issue description

**Currently :**
Image workbench :
- Image_Open: Open the img in a (bad) image viewer.
- Image_CreateImagePlane: Create a plane and put the selected img in it.
- Image_Scale: a Dialog opens to scale the image.
Core :
- File/Open + File/import : both call Image_Open.
- Double clicking on the Tree element triggers the transform enabling setting the image at correct position.

**Remarks :**
- Image_Open is useless. It only opens the picture in a bad image viewer. It is misleading and bad UI because what the user want is Image_CreateImagePlane.
- Having a workbench for only 1-2 tools is overkill + clutter the workbench selector.

**Suggestion :**
- Delete the Image workbench.
- Move the Image code to Core.
- The image viewer is removed. All tools from the toolbar are removed.
- File/Open + File/import + Paste with an image + drag drop an img, all call Image_CreateImagePlane.
- Double clicking the ImagePlane in tree + in 3DView opens a TaskBox containing the necessary for placement + transform + scale.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
> In the Tools menu we have the image creation function and there we can move the function to map an image onto a plane.

@wwmayer you mean `src\Tools\ImageTools\ImageConv` right ? So necessary files should be put in `src\tools\ImageTools\imagePlane` for instance?

But the command CmdCreateImagePlane, it should still be in one of the command tools in src/gui Like CommandStd.cpp?

Currently the Open command connects to the `Py::Object open` of the `ImageGui Module` in a generic way through : `StdCmdOpen` then  `Application::open` which then calls `Command::doCommand(Command::App, "%s.open(u\"%s\")", Module, unicodepath.c_str());`

So I'm unsure how to connect the CmdCreateImagePlane command in here. Should we add an `else if (File.hasExtension("png") || File.hasExtension("jpg") || ...)` in the `Application::open`?

**Comment by wwmayer** [comment]
> you mean src\Tools\ImageTools\ImageConv right ?

No. I meant the function in FreeCAD: Tools > Save picture, that creates an image of the currently active view. I thought about adding a function to the Tools menu to also load an image file. Using the global open/import mechanism is an option too but it causes a lot of extra work.

ImageConv has been removed recently and it was a utility to convert between several image formats and had an option to write XPM files to a .cpp file. The utility has become obsolete since we are using Qt's resource framework and switched to the SVG format for most of our icons.

> Should we add an else if (File.hasExtension("png") || File.hasExtension("jpg") || ...) in the Application::open?

No. Like for any other module the core system must register the image file types and define a module name (here FreeCADGui) that is supposed to load them.

**Comment by PaddleStroke** [comment]
Thanks for the feedback. And it has already been done I see ! That's great. 
https://github.com/FreeCAD/FreeCAD/pull/8955

**Comment by PaddleStroke** [comment]
What do you think about this taskbox to trigger when imagePlane is double clicked : 
![image](https://user-images.githubusercontent.com/19984177/226207189-45e2df04-663c-41b3-b159-d4b15c25bb4c.png)

The first rectangle being a 'feature picker'. 
- It displays the name of current orientation plane.
- When clicked it a) opens a menu with 'XY plane' 'XZ plane' & 'YZ plane'. and b) shows the planes on the 3d view
- When user select a feature on the 3d viewer, the edition stops and the newly selected orientation is displayed.

**Comment by chennes** [comment]
Can you provide instead an X-scale and a Y-scale with a link that turns on and off uniform scaling (like in Inkscape, for example)?

**Comment by bambukouk** [comment]
What seems to be missing as well is setting image transparency.
I use all my images transparent and I believe it can and should be done at the point of importing, please

**Comment by PLChris** [comment]
We could then also have a slider or similar for the backlight preference.

**Comment by bambukouk** [comment]
Is backlight preference set globally for Display, or is it specific to image only?
(and yes I use both transparency and backlight for my images)

**Comment by sliptonic** [comment]
what's the inputbox control for orientation (plane)?  
How would the user align the image to the camera position?  (Yes, it's a border case but might as well include it here)

**Comment by chennes** [comment]
> setting position at the point of import is un-important
> I always have to move the image afterwards anyway.

Isn't that what we are talking about here? The interface for working with the image once it's been imported?

**Comment by bambukouk** [comment]
> ...How would the user align the image to the camera position? (Yes, it's a border case but might as well include it here)

wouldn't it be better that such a "marginal" case is handled by use of normal placement tool rather than clutter interface for vast majority of users?

**Comment by adrianinsaval** [comment]
isn't it better to reuse the dialog and concepts of the attachment dialog rather than making an independent dialog here for positioning the image plane? This will also make it more consistent with other object creation dialogs so the user only needs to learn to use this once.
Then above that we can have a widget with scaling and transparency options.

**Comment by bambukouk** [comment]
`> isn't it better to reuse the dialog and concepts of the attachment dialog rather than making an independent dialog here for positioning the image plane? `

in my view no, because the needs are different...
How do you propose to `drag the image on the screen` using placement dialogue?
there needs to be a combination of precise X,Y placement as well as manually dragging on the screen

**Comment by adrianinsaval** [comment]
Does the current method allow dragging? You can use the transform tool if you wish to drag things around. In the future we could better unify the attachment, placement and transform dialogs. This would then benefit all objects using that dialog

**Comment by sliptonic** [comment]
> > ...How would the user align the image to the camera position? (Yes, it's a border case but might as well include it here)
> 
> wouldn't it be better that such a "marginal" case is handled by use of normal placement tool rather than clutter interface for vast majority of users?

Instead of having three controls (radio buttons) for the three planes, have one combobox with the alignment options (XY XZ, YZ, Camera)  and an apply button.  If other alignment options are desired in the future, they're easily added.

**Comment by adrianinsaval** [comment]
Is there something still open here? should we not close this now?

**Comment by chennes** [comment]
I agree: if there are still a few lingering problems we need specific Issues to address them, they'll be lost here.
