### ISSUE TITLE
Problem:  Customize Commands doesn't do anything

### ISSUE THREAD

**Issue by sliptonic** [FreeCAD/FreeCAD#9028]
When the user launches the Customize dialog (tools->customize) The first tab shown is 'commands'.  Nothing on this screen can be changed or customized.   This is confusing.

There may be value in being able to explore the available commands but it really isn't a customization.

Is there any value in preserving this feature?  If so, where should it live to be more intuitive?

![Image](https://user-images.githubusercontent.com/538057/227528976-ad9e234f-4d4c-4e85-ae4f-646cd7146d51.png)

**Comment by adrianinsaval** [comment]
yeah this tab should be removed

**Comment by chennes** [comment]
Agreed (and @Pesc0 the ampersands show the accelerator key for the command, it's Qt's syntax that for some reason we are displaying to end users 🤷 ).

**Comment by Pesc0** [comment]
> the ampersands show the accelerator key for the command

Right, I think that should be removed, it's cumbersome to read and un-intuitive. Perhaps the `keyboard` tab, where accelerator keys are set, can receive a refresh similar to the workbench tab. Also, assuming I didn't misunderstand, it doesn't always work:

![Screenshot from 2023-03-28 18-59-25](https://user-images.githubusercontent.com/54720203/228313978-be00579f-3d7a-4871-8526-dabbeb43685c.png) 
![Screenshot from 2023-03-28 18-59-16](https://user-images.githubusercontent.com/54720203/228314010-57b91fde-95ef-4527-826e-aba6459b90e9.png)

On that note: to be honest I would love to see the whole customize menu moved into preferences. I think having all the settings in a single place is good for usability and for new users to discover what's available. I know it took a while for me to discover I could create custom toolbars and move stuff around in the interface, and that's because the toolbar settings were not under the traditional 'preferences' but (hidden) under 'customize' instead. 

And, speaking of settings, further still from the topic of this issue, it's super weird that some settings are visible only when a workbench is loaded. Creates quite a bit of confusion for someone new.

**Comment by chennes** [comment]
> And, speaking of settings, further still from the topic of this issue, it's super weird that some settings are visible only when a workbench is loaded.

That was actually the original reason the Workbenches preference page was created -- the idea was that if you went looking for your preferences and didn't see your workbench, your next best option would be to click on "Workbenches" which had a short explanatory text at the top telling you to load your workbench. It helped reduce that particular help question a ton.

**Comment by Pesc0** [comment]
Oh, I thought lazy loading was just to speed up application launch. IMO having to resort to 'fallbacks'...
> your next best option would be to click on "Workbenches"

means something is not particularly intuitive about the process, and the user is forced to proceed by trial and error. Something like this would be much more user friendly I think

![POC](https://user-images.githubusercontent.com/54720203/228363282-c762ceae-be17-420a-8a39-ecb715587753.png)

**Comment by adrianinsaval** [comment]
That's a good idea but then we need a system for addons to register that they have a preference page without loading them. Could be something to add to package.xml maybe? I think you should open a separate issue for this conversation though

**Comment by Pesc0** [comment]
Right, moving this to another issue tomorrow. Regarding this topic I see we agree on removing the "Commands" tab.

**Comment by sasobadovinac** [comment]
Such Commands tabs in Customize dialogs are normally used to build custom toolbars by drag and drop of the commands, this is by itself actually very common in UI/UX design, but indeed in FC the drag and drop functionality is not working and the editing of toolbars is done from the Toolbars tab.

**Comment by sliptonic** [comment]
Any reason not to move ahead with removing the Commands tab?

**Comment by chennes** [comment]
It literally does nothing -- I'm good with removing it.

**Comment by sasobadovinac** [comment]
My above comment about it should be seen only as informational on how such a commands tab is normally used, since in FC it is actually not working I am not objecting on its removal...

**Comment by Pesc0** [comment]
#9110 can be merged then?
